// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package teldb

import (
	"github.com/x0ryz/hakobu/internal/secret"
)

type TelemetryEvent struct {
	ID        int64
	AppName   string
	Kind      string
	Level     string
	Message   secret.String
	Payload   secret.String
	CreatedAt string
}
