// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package teldb

import (
	"github.com/x0ryz/hakobu/internal/secret"
)

type Sample struct {
	Target    string
	Res       int64
	Slot      int64
	Ts        int64
	Cpu       float64
	CpuMax    float64
	CpuLimit  float64
	Mem       int64
	MemMax    int64
	MemLimit  int64
	NetRx     float64
	NetTx     float64
	DiskRead  float64
	DiskWrite float64
	Load      float64
	DiskUsed  int64
	DiskTotal int64
}

type TelemetryEvent struct {
	ID        int64
	AppName   string
	Kind      string
	Level     string
	Message   secret.String
	Payload   secret.String
	CreatedAt string
	TraceID   string
}

type Trace struct {
	ID         int64
	AppName    string
	TraceID    string
	Name       string
	Status     string
	HttpStatus int64
	DurationMs int64
	SlowSpan   secret.String
	Payload    secret.String
	CreatedAt  int64
}

type TraceRoute struct {
	AppName string
	Name    string
	Hour    int64
	Count   int64
	Errors  int64
	TotalMs int64
	B0      int64
	B1      int64
	B2      int64
	B3      int64
	B4      int64
	B5      int64
	B6      int64
	B7      int64
	B8      int64
	B9      int64
	B10     int64
}
