// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package teldb

import (
	"context"

	"github.com/x0ryz/hakobu/internal/secret"
)

const countTrace = `-- name: CountTrace :exec
INSERT INTO trace_routes (app_name, name, hour, count, errors, total_ms, b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10)
VALUES (?1, ?2, ?3, 1, ?4, ?5,
	?6 = 0, ?6 = 1, ?6 = 2, ?6 = 3, ?6 = 4, ?6 = 5,
	?6 = 6, ?6 = 7, ?6 = 8, ?6 = 9, ?6 = 10)
ON CONFLICT (app_name, hour, name) DO UPDATE SET
	count = count + 1, errors = errors + excluded.errors, total_ms = total_ms + excluded.total_ms,
	b0 = b0 + excluded.b0, b1 = b1 + excluded.b1, b2 = b2 + excluded.b2, b3 = b3 + excluded.b3,
	b4 = b4 + excluded.b4, b5 = b5 + excluded.b5, b6 = b6 + excluded.b6, b7 = b7 + excluded.b7,
	b8 = b8 + excluded.b8, b9 = b9 + excluded.b9, b10 = b10 + excluded.b10
`

type CountTraceParams struct {
	AppName string
	Name    string
	Hour    int64
	Errors  int64
	Ms      int64
	Bucket  interface{}
}

func (q *Queries) CountTrace(ctx context.Context, arg CountTraceParams) error {
	_, err := q.db.ExecContext(ctx, countTrace,
		arg.AppName,
		arg.Name,
		arg.Hour,
		arg.Errors,
		arg.Ms,
		arg.Bucket,
	)
	return err
}

const countTraceRoutes = `-- name: CountTraceRoutes :one
SELECT count(*) FROM trace_routes WHERE app_name = ? AND hour = ?
`

type CountTraceRoutesParams struct {
	AppName string
	Hour    int64
}

func (q *Queries) CountTraceRoutes(ctx context.Context, arg CountTraceRoutesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTraceRoutes, arg.AppName, arg.Hour)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTelemetryEvent = `-- name: CreateTelemetryEvent :exec
INSERT INTO telemetry_events (app_name, kind, level, message, payload, trace_id) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTelemetryEventParams struct {
	AppName string
	Kind    string
	Level   string
	Message secret.String
	Payload secret.String
	TraceID string
}

func (q *Queries) CreateTelemetryEvent(ctx context.Context, arg CreateTelemetryEventParams) error {
	_, err := q.db.ExecContext(ctx, createTelemetryEvent,
		arg.AppName,
		arg.Kind,
		arg.Level,
		arg.Message,
		arg.Payload,
		arg.TraceID,
	)
	return err
}

const createTrace = `-- name: CreateTrace :exec
INSERT INTO traces (app_name, trace_id, name, status, http_status, duration_ms, slow_span, payload, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTraceParams struct {
	AppName    string
	TraceID    string
	Name       string
	Status     string
	HttpStatus int64
	DurationMs int64
	SlowSpan   secret.String
	Payload    secret.String
	CreatedAt  int64
}

func (q *Queries) CreateTrace(ctx context.Context, arg CreateTraceParams) error {
	_, err := q.db.ExecContext(ctx, createTrace,
		arg.AppName,
		arg.TraceID,
		arg.Name,
		arg.Status,
		arg.HttpStatus,
		arg.DurationMs,
		arg.SlowSpan,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const deleteSamplesOf = `-- name: DeleteSamplesOf :exec
DELETE FROM samples WHERE target = ?
`

func (q *Queries) DeleteSamplesOf(ctx context.Context, target string) error {
	_, err := q.db.ExecContext(ctx, deleteSamplesOf, target)
	return err
}

const deleteTelemetryOfApp = `-- name: DeleteTelemetryOfApp :exec
DELETE FROM telemetry_events WHERE app_name = ?
`

func (q *Queries) DeleteTelemetryOfApp(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteTelemetryOfApp, appName)
	return err
}

const deleteTraceRoutesOfApp = `-- name: DeleteTraceRoutesOfApp :exec
DELETE FROM trace_routes WHERE app_name = ?
`

func (q *Queries) DeleteTraceRoutesOfApp(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteTraceRoutesOfApp, appName)
	return err
}

const deleteTracesOfApp = `-- name: DeleteTracesOfApp :exec
DELETE FROM traces WHERE app_name = ?
`

func (q *Queries) DeleteTracesOfApp(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteTracesOfApp, appName)
	return err
}

const getTelemetryEvent = `-- name: GetTelemetryEvent :one
SELECT id, app_name, kind, level, message, payload, created_at, trace_id FROM telemetry_events WHERE id = ? AND app_name = ?
`

type GetTelemetryEventParams struct {
	ID      int64
	AppName string
}

func (q *Queries) GetTelemetryEvent(ctx context.Context, arg GetTelemetryEventParams) (TelemetryEvent, error) {
	row := q.db.QueryRowContext(ctx, getTelemetryEvent, arg.ID, arg.AppName)
	var i TelemetryEvent
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Kind,
		&i.Level,
		&i.Message,
		&i.Payload,
		&i.CreatedAt,
		&i.TraceID,
	)
	return i, err
}

const getTrace = `-- name: GetTrace :one
SELECT id, app_name, trace_id, name, status, http_status, duration_ms, slow_span, payload, created_at FROM traces WHERE id = ? AND app_name = ?
`

type GetTraceParams struct {
	ID      int64
	AppName string
}

func (q *Queries) GetTrace(ctx context.Context, arg GetTraceParams) (Trace, error) {
	row := q.db.QueryRowContext(ctx, getTrace, arg.ID, arg.AppName)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.TraceID,
		&i.Name,
		&i.Status,
		&i.HttpStatus,
		&i.DurationMs,
		&i.SlowSpan,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const hasTraceRoute = `-- name: HasTraceRoute :one
SELECT EXISTS (SELECT 1 FROM trace_routes WHERE app_name = ? AND hour = ? AND name = ?)
`

type HasTraceRouteParams struct {
	AppName string
	Hour    int64
	Name    string
}

func (q *Queries) HasTraceRoute(ctx context.Context, arg HasTraceRouteParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasTraceRoute, arg.AppName, arg.Hour, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lastTelemetryOfKind = `-- name: LastTelemetryOfKind :one
SELECT created_at FROM telemetry_events WHERE app_name = ? AND kind = ? ORDER BY id DESC LIMIT 1
`

type LastTelemetryOfKindParams struct {
	AppName string
	Kind    string
}

func (q *Queries) LastTelemetryOfKind(ctx context.Context, arg LastTelemetryOfKindParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lastTelemetryOfKind, arg.AppName, arg.Kind)
	var created_at string
	err := row.Scan(&created_at)
	return created_at, err
}

const latestSamples = `-- name: LatestSamples :many
SELECT target, res, slot, ts, cpu, cpu_max, cpu_limit, mem, mem_max, mem_limit, net_rx, net_tx, disk_read, disk_write, load, disk_used, disk_total FROM samples WHERE res = ? AND ts >= ? ORDER BY ts
`

type LatestSamplesParams struct {
	Res int64
	Ts  int64
}

func (q *Queries) LatestSamples(ctx context.Context, arg LatestSamplesParams) ([]Sample, error) {
	rows, err := q.db.QueryContext(ctx, latestSamples, arg.Res, arg.Ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sample
	for rows.Next() {
		var i Sample
		if err := rows.Scan(
			&i.Target,
			&i.Res,
			&i.Slot,
			&i.Ts,
			&i.Cpu,
			&i.CpuMax,
			&i.CpuLimit,
			&i.Mem,
			&i.MemMax,
			&i.MemLimit,
			&i.NetRx,
			&i.NetTx,
			&i.DiskRead,
			&i.DiskWrite,
			&i.Load,
			&i.DiskUsed,
			&i.DiskTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSamples = `-- name: ListSamples :many
SELECT target, res, slot, ts, cpu, cpu_max, cpu_limit, mem, mem_max, mem_limit, net_rx, net_tx, disk_read, disk_write, load, disk_used, disk_total FROM samples WHERE target = ? AND res = ? AND ts >= ? ORDER BY ts
`

type ListSamplesParams struct {
	Target string
	Res    int64
	Ts     int64
}

func (q *Queries) ListSamples(ctx context.Context, arg ListSamplesParams) ([]Sample, error) {
	rows, err := q.db.QueryContext(ctx, listSamples, arg.Target, arg.Res, arg.Ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sample
	for rows.Next() {
		var i Sample
		if err := rows.Scan(
			&i.Target,
			&i.Res,
			&i.Slot,
			&i.Ts,
			&i.Cpu,
			&i.CpuMax,
			&i.CpuLimit,
			&i.Mem,
			&i.MemMax,
			&i.MemLimit,
			&i.NetRx,
			&i.NetTx,
			&i.DiskRead,
			&i.DiskWrite,
			&i.Load,
			&i.DiskUsed,
			&i.DiskTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTelemetryEvents = `-- name: ListTelemetryEvents :many
SELECT id, app_name, kind, level, message, payload, created_at, trace_id FROM telemetry_events WHERE app_name = ? ORDER BY id DESC LIMIT ?
`

type ListTelemetryEventsParams struct {
	AppName string
	Limit   int64
}

func (q *Queries) ListTelemetryEvents(ctx context.Context, arg ListTelemetryEventsParams) ([]TelemetryEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTelemetryEvents, arg.AppName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemetryEvent
	for rows.Next() {
		var i TelemetryEvent
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.Kind,
			&i.Level,
			&i.Message,
			&i.Payload,
			&i.CreatedAt,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTraceRoutes = `-- name: ListTraceRoutes :many
SELECT app_name, name, hour, count, errors, total_ms, b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10 FROM trace_routes WHERE app_name = ? AND hour >= ?
`

type ListTraceRoutesParams struct {
	AppName string
	Hour    int64
}

func (q *Queries) ListTraceRoutes(ctx context.Context, arg ListTraceRoutesParams) ([]TraceRoute, error) {
	rows, err := q.db.QueryContext(ctx, listTraceRoutes, arg.AppName, arg.Hour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TraceRoute
	for rows.Next() {
		var i TraceRoute
		if err := rows.Scan(
			&i.AppName,
			&i.Name,
			&i.Hour,
			&i.Count,
			&i.Errors,
			&i.TotalMs,
			&i.B0,
			&i.B1,
			&i.B2,
			&i.B3,
			&i.B4,
			&i.B5,
			&i.B6,
			&i.B7,
			&i.B8,
			&i.B9,
			&i.B10,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTraces = `-- name: ListTraces :many
SELECT id, app_name, trace_id, name, status, http_status, duration_ms, slow_span, created_at
FROM traces WHERE app_name = ? ORDER BY id DESC LIMIT ?
`

type ListTracesParams struct {
	AppName string
	Limit   int64
}

type ListTracesRow struct {
	ID         int64
	AppName    string
	TraceID    string
	Name       string
	Status     string
	HttpStatus int64
	DurationMs int64
	SlowSpan   secret.String
	CreatedAt  int64
}

func (q *Queries) ListTraces(ctx context.Context, arg ListTracesParams) ([]ListTracesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTraces, arg.AppName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracesRow
	for rows.Next() {
		var i ListTracesRow
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.TraceID,
			&i.Name,
			&i.Status,
			&i.HttpStatus,
			&i.DurationMs,
			&i.SlowSpan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneEvents = `-- name: PruneEvents :exec
DELETE FROM telemetry_events WHERE created_at < ?
`

func (q *Queries) PruneEvents(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, pruneEvents, createdAt)
	return err
}

const pruneLogs = `-- name: PruneLogs :exec
DELETE FROM telemetry_events WHERE kind = 'log' AND created_at < ?
`

func (q *Queries) PruneLogs(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, pruneLogs, createdAt)
	return err
}

const pruneSamples = `-- name: PruneSamples :exec
DELETE FROM samples WHERE ts < ?
`

func (q *Queries) PruneSamples(ctx context.Context, ts int64) error {
	_, err := q.db.ExecContext(ctx, pruneSamples, ts)
	return err
}

const pruneTraceRoutes = `-- name: PruneTraceRoutes :exec
DELETE FROM trace_routes WHERE hour < ?
`

func (q *Queries) PruneTraceRoutes(ctx context.Context, hour int64) error {
	_, err := q.db.ExecContext(ctx, pruneTraceRoutes, hour)
	return err
}

const pruneTraces = `-- name: PruneTraces :exec
DELETE FROM traces WHERE created_at < ?
`

func (q *Queries) PruneTraces(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneTraces, createdAt)
	return err
}

const putSample = `-- name: PutSample :exec
INSERT INTO samples (target, res, slot, ts, cpu, cpu_max, cpu_limit, mem, mem_max, mem_limit, net_rx, net_tx, disk_read, disk_write, load, disk_used, disk_total)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (target, res, slot) DO UPDATE SET
	ts = excluded.ts, cpu = excluded.cpu, cpu_max = excluded.cpu_max, cpu_limit = excluded.cpu_limit,
	mem = excluded.mem, mem_max = excluded.mem_max, mem_limit = excluded.mem_limit,
	net_rx = excluded.net_rx, net_tx = excluded.net_tx, disk_read = excluded.disk_read, disk_write = excluded.disk_write,
	load = excluded.load, disk_used = excluded.disk_used, disk_total = excluded.disk_total
`

type PutSampleParams struct {
	Target    string
	Res       int64
	Slot      int64
	Ts        int64
	Cpu       float64
	CpuMax    float64
	CpuLimit  float64
	Mem       int64
	MemMax    int64
	MemLimit  int64
	NetRx     float64
	NetTx     float64
	DiskRead  float64
	DiskWrite float64
	Load      float64
	DiskUsed  int64
	DiskTotal int64
}

func (q *Queries) PutSample(ctx context.Context, arg PutSampleParams) error {
	_, err := q.db.ExecContext(ctx, putSample,
		arg.Target,
		arg.Res,
		arg.Slot,
		arg.Ts,
		arg.Cpu,
		arg.CpuMax,
		arg.CpuLimit,
		arg.Mem,
		arg.MemMax,
		arg.MemLimit,
		arg.NetRx,
		arg.NetTx,
		arg.DiskRead,
		arg.DiskWrite,
		arg.Load,
		arg.DiskUsed,
		arg.DiskTotal,
	)
	return err
}

const summarizeSamples = `-- name: SummarizeSamples :many
SELECT target,
	CAST(avg(cpu) AS REAL) AS cpu, CAST(max(cpu_max) AS REAL) AS cpu_max, CAST(max(cpu_limit) AS REAL) AS cpu_limit,
	CAST(avg(mem) AS INTEGER) AS mem, CAST(max(mem_max) AS INTEGER) AS mem_max, CAST(max(mem_limit) AS INTEGER) AS mem_limit,
	CAST(avg(net_rx) AS REAL) AS net_rx, CAST(avg(net_tx) AS REAL) AS net_tx,
	CAST(avg(disk_read) AS REAL) AS disk_read, CAST(avg(disk_write) AS REAL) AS disk_write,
	CAST(avg(load) AS REAL) AS load, CAST(max(disk_used) AS INTEGER) AS disk_used, CAST(max(disk_total) AS INTEGER) AS disk_total
FROM samples WHERE res = ? AND ts >= ? AND ts < ? GROUP BY target
`

type SummarizeSamplesParams struct {
	Res  int64
	Ts   int64
	Ts_2 int64
}

type SummarizeSamplesRow struct {
	Target    string
	Cpu       float64
	CpuMax    float64
	CpuLimit  float64
	Mem       int64
	MemMax    int64
	MemLimit  int64
	NetRx     float64
	NetTx     float64
	DiskRead  float64
	DiskWrite float64
	Load      float64
	DiskUsed  int64
	DiskTotal int64
}

func (q *Queries) SummarizeSamples(ctx context.Context, arg SummarizeSamplesParams) ([]SummarizeSamplesRow, error) {
	rows, err := q.db.QueryContext(ctx, summarizeSamples, arg.Res, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarizeSamplesRow
	for rows.Next() {
		var i SummarizeSamplesRow
		if err := rows.Scan(
			&i.Target,
			&i.Cpu,
			&i.CpuMax,
			&i.CpuLimit,
			&i.Mem,
			&i.MemMax,
			&i.MemLimit,
			&i.NetRx,
			&i.NetTx,
			&i.DiskRead,
			&i.DiskWrite,
			&i.Load,
			&i.DiskUsed,
			&i.DiskTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traceByTraceID = `-- name: TraceByTraceID :one
SELECT id FROM traces WHERE app_name = ? AND trace_id = ? ORDER BY id DESC LIMIT 1
`

type TraceByTraceIDParams struct {
	AppName string
	TraceID string
}

func (q *Queries) TraceByTraceID(ctx context.Context, arg TraceByTraceIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, traceByTraceID, arg.AppName, arg.TraceID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
