// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package teldb

import (
	"context"

	"github.com/x0ryz/hakobu/internal/secret"
)

const createTelemetryEvent = `-- name: CreateTelemetryEvent :exec
INSERT INTO telemetry_events (app_name, kind, level, message, payload) VALUES (?, ?, ?, ?, ?)
`

type CreateTelemetryEventParams struct {
	AppName string
	Kind    string
	Level   string
	Message secret.String
	Payload secret.String
}

func (q *Queries) CreateTelemetryEvent(ctx context.Context, arg CreateTelemetryEventParams) error {
	_, err := q.db.ExecContext(ctx, createTelemetryEvent,
		arg.AppName,
		arg.Kind,
		arg.Level,
		arg.Message,
		arg.Payload,
	)
	return err
}

const deleteTelemetryOfApp = `-- name: DeleteTelemetryOfApp :exec
DELETE FROM telemetry_events WHERE app_name = ?
`

func (q *Queries) DeleteTelemetryOfApp(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteTelemetryOfApp, appName)
	return err
}

const getTelemetryEvent = `-- name: GetTelemetryEvent :one
SELECT id, app_name, kind, level, message, payload, created_at FROM telemetry_events WHERE id = ? AND app_name = ?
`

type GetTelemetryEventParams struct {
	ID      int64
	AppName string
}

func (q *Queries) GetTelemetryEvent(ctx context.Context, arg GetTelemetryEventParams) (TelemetryEvent, error) {
	row := q.db.QueryRowContext(ctx, getTelemetryEvent, arg.ID, arg.AppName)
	var i TelemetryEvent
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Kind,
		&i.Level,
		&i.Message,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const lastTelemetryOfKind = `-- name: LastTelemetryOfKind :one
SELECT created_at FROM telemetry_events WHERE app_name = ? AND kind = ? ORDER BY id DESC LIMIT 1
`

type LastTelemetryOfKindParams struct {
	AppName string
	Kind    string
}

func (q *Queries) LastTelemetryOfKind(ctx context.Context, arg LastTelemetryOfKindParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lastTelemetryOfKind, arg.AppName, arg.Kind)
	var created_at string
	err := row.Scan(&created_at)
	return created_at, err
}

const listTelemetryEvents = `-- name: ListTelemetryEvents :many
SELECT id, app_name, kind, level, message, payload, created_at FROM telemetry_events WHERE app_name = ? ORDER BY id DESC LIMIT ?
`

type ListTelemetryEventsParams struct {
	AppName string
	Limit   int64
}

func (q *Queries) ListTelemetryEvents(ctx context.Context, arg ListTelemetryEventsParams) ([]TelemetryEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTelemetryEvents, arg.AppName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemetryEvent
	for rows.Next() {
		var i TelemetryEvent
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.Kind,
			&i.Level,
			&i.Message,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneEvents = `-- name: PruneEvents :exec
DELETE FROM telemetry_events WHERE created_at < ?
`

func (q *Queries) PruneEvents(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, pruneEvents, createdAt)
	return err
}

const pruneLogs = `-- name: PruneLogs :exec
DELETE FROM telemetry_events WHERE kind = 'log' AND created_at < ?
`

func (q *Queries) PruneLogs(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, pruneLogs, createdAt)
	return err
}
