// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/x0ryz/hakobu/internal/secret"
)

type App struct {
	ID              int64
	ProjectID       int64
	ProjectName     string
	Name            string
	Repo            string
	Domain          string
	DnsZoneID       string
	DnsRecordID     string
	Port            int64
	ContainerPort   int64
	LivePort        int64
	BuildPath       string
	BuildStrategy   string
	ActiveSlot      string
	Env             secret.String
	SentryKey       secret.String
	HealthCheckPath string
	LinkedDB        string
	LinkedStorage   string
	ShareVolumes    int64
	MemoryMB        int64
	Cpus            float64
	SnapshotDB      string
	SnapshotAt      string
}

type AppRecord struct {
	ID              int64
	ProjectID       int64
	Name            string
	Repo            string
	Domain          string
	DnsZoneID       string
	DnsRecordID     string
	Port            int64
	ContainerPort   int64
	LivePort        int64
	BuildPath       string
	BuildStrategy   string
	ActiveSlot      string
	Env             secret.String
	SentryKey       secret.String
	HealthCheckPath string
	LinkedDB        string
	LinkedStorage   string
	ShareVolumes    int64
	MemoryMB        int64
	Cpus            float64
	SnapshotDB      string
	SnapshotAt      string
}

type Backup struct {
	ID          int64
	Database    string
	ObjectKey   string
	Parts       int64
	SizeBytes   int64
	SHA256      string
	CreatedAt   string
	VerifiedAt  string
	VerifyError string
	Tables      int64
	FileKey     secret.String
}

type Cloudflare struct {
	ID            int64
	ApiToken      secret.String
	AccountID     string
	TunnelID      string
	TunnelToken   secret.String
	PanelZoneID   string
	PanelRecordID string
	BackupBucket  string
}

type Database struct {
	Name      string
	ProjectID int64
	User      string
	Password  secret.String
}

type DeployLog struct {
	ID        int64
	AppName   string
	Trigger   string
	Status    string
	Output    secret.String
	CreatedAt string
}

type GitHubApp struct {
	ID            int64
	AppID         int64
	Slug          string
	PrivateKey    secret.String
	WebhookSecret secret.String
	ClientID      string
	ClientSecret  secret.String
}

type Notify struct {
	ID           int64
	Email        string
	SenderDomain string
	ZoneID       string
	AddedAddress int64
	RoutedDomain string
	SenderName   string
}

type OAuthClient struct {
	ID           string
	Name         string
	RedirectURIs string
	CreatedAt    string
}

type OAuthGrant struct {
	ID          int64
	ClientID    string
	ClientName  string
	RedirectURI string
	Scope       string
	GitHubID    int64
	CreatedAt   string
	LastUsedAt  string
}

type OAuthToken struct {
	ID            string
	GrantID       int64
	Kind          string
	CodeChallenge string
	ExpiresAt     string
	UsedAt        string
}

type Owner struct {
	ID          int64
	GitHubID    int64
	GitHubLogin string
	GitHubEmail string
}

type Project struct {
	ID        int64
	Name      string
	SharedEnv secret.String
}

type SealedVar struct {
	Scope string
	Owner string
	Key   string
	Value secret.String
}

type Session struct {
	ID         string
	GitHubID   int64
	SignedInAt string
	ExpiresAt  string
}

type Storage struct {
	Name            string
	ProjectID       int64
	Provider        string
	AccountID       string
	Endpoint        string
	AccessKeyID     string
	SecretAccessKey secret.String
	Bucket          string
	Region          string
}

type Volume struct {
	AppName   string
	Name      string
	MountPath string
}

type VolumeBackup struct {
	ID          int64
	AppName     string
	Volume      string
	ObjectKey   string
	Parts       int64
	SizeBytes   int64
	SHA256      string
	FileKey     secret.String
	CreatedAt   string
	VerifiedAt  string
	VerifyError string
	Files       int64
}

type Watchdog struct {
	ID            int64
	Script        string
	KvNamespaceID string
	CreatedAt     string
	Targets       string
	D1DatabaseID  string
}

type WatchdogOff struct {
	ID int64
}

type WebhookDelivery struct {
	ID        string
	CreatedAt string
}

type Worker struct {
	AppName string
	Name    string
	Command secret.String
	Env     secret.String
}
