// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/x0ryz/hakobu/internal/secret"
)

type App struct {
	ID              int64
	ProjectID       int64
	ProjectName     string
	Name            string
	Repo            string
	Domain          string
	DnsZoneID       string
	DnsRecordID     string
	Port            int64
	ContainerPort   int64
	LivePort        int64
	BuildPath       string
	BuildStrategy   string
	ActiveSlot      string
	Env             secret.String
	SentryKey       secret.String
	HealthCheckPath string
	LinkedDB        string
	LinkedStorage   string
	ShareVolumes    int64
	MemoryMB        int64
	Cpus            float64
}

type AppRecord struct {
	ID              int64
	ProjectID       int64
	Name            string
	Repo            string
	Domain          string
	DnsZoneID       string
	DnsRecordID     string
	Port            int64
	ContainerPort   int64
	LivePort        int64
	BuildPath       string
	BuildStrategy   string
	ActiveSlot      string
	Env             secret.String
	SentryKey       secret.String
	HealthCheckPath string
	LinkedDB        string
	LinkedStorage   string
	ShareVolumes    int64
	MemoryMB        int64
	Cpus            float64
}

type Backup struct {
	ID          int64
	Database    string
	Storage     string
	ObjectKey   string
	SizeBytes   int64
	CreatedAt   string
	VerifiedAt  string
	VerifyError string
	Tables      int64
}

type Cloudflare struct {
	ID            int64
	AccessToken   secret.String
	RefreshToken  secret.String
	ExpiresAt     string
	AccountID     string
	TunnelID      string
	TunnelToken   secret.String
	PanelZoneID   string
	PanelRecordID string
}

type Database struct {
	Name          string
	ProjectID     int64
	User          string
	Password      secret.String
	BackupStorage string
}

type DeployLog struct {
	ID        int64
	AppName   string
	Trigger   string
	Status    string
	Output    string
	CreatedAt string
}

type GitHubApp struct {
	ID            int64
	AppID         int64
	Slug          string
	PrivateKey    secret.String
	WebhookSecret secret.String
	ClientID      string
	ClientSecret  secret.String
}

type Owner struct {
	ID          int64
	GitHubLogin string
}

type Project struct {
	ID        int64
	Name      string
	SharedEnv secret.String
}

type Session struct {
	ID          string
	GitHubLogin string
	ExpiresAt   string
}

type Storage struct {
	Name            string
	ProjectID       int64
	Provider        string
	AccountID       string
	Endpoint        string
	AccessKeyID     string
	SecretAccessKey secret.String
	Bucket          string
	Region          string
}

type TelemetryEvent struct {
	ID        int64
	AppName   string
	Kind      string
	Level     string
	Message   string
	Payload   string
	CreatedAt string
}

type Volume struct {
	AppName   string
	Name      string
	MountPath string
}

type Worker struct {
	AppName string
	Name    string
	Command string
	Env     secret.String
}
