// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/x0ryz/hakobu/internal/secret"
)

type App struct {
	ID              int64
	ProjectID       int64
	ProjectName     string
	Name            string
	Repo            string
	Domain          string
	DnsZoneID       string
	DnsRecordID     string
	Port            int64
	ContainerPort   int64
	LivePort        int64
	BuildPath       string
	BuildStrategy   string
	ActiveSlot      string
	Env             secret.String
	SentryKey       secret.String
	HealthCheckPath string
	LinkedDB        string
	LinkedStorage   string
	ShareVolumes    int64
	MemoryMB        int64
	Cpus            float64
	SnapshotDB      string
	SnapshotAt      string
}

type AppRecord struct {
	ID              int64
	ProjectID       int64
	Name            string
	Repo            string
	Domain          string
	DnsZoneID       string
	DnsRecordID     string
	Port            int64
	ContainerPort   int64
	LivePort        int64
	BuildPath       string
	BuildStrategy   string
	ActiveSlot      string
	Env             secret.String
	SentryKey       secret.String
	HealthCheckPath string
	LinkedDB        string
	LinkedStorage   string
	ShareVolumes    int64
	MemoryMB        int64
	Cpus            float64
	SnapshotDB      string
	SnapshotAt      string
}

type Backup struct {
	ID          int64
	Database    string
	ObjectKey   string
	Parts       int64
	SizeBytes   int64
	SHA256      string
	CreatedAt   string
	VerifiedAt  string
	VerifyError string
	Tables      int64
}

type Cloudflare struct {
	ID            int64
	ApiToken      secret.String
	AccountID     string
	TunnelID      string
	TunnelToken   secret.String
	PanelZoneID   string
	PanelRecordID string
	BackupBucket  string
}

type Database struct {
	Name      string
	ProjectID int64
	User      string
	Password  secret.String
}

type DeployLog struct {
	ID        int64
	AppName   string
	Trigger   string
	Status    string
	Output    secret.String
	CreatedAt string
}

type GitHubApp struct {
	ID            int64
	AppID         int64
	Slug          string
	PrivateKey    secret.String
	WebhookSecret secret.String
	ClientID      string
	ClientSecret  secret.String
}

type Owner struct {
	ID          int64
	GitHubID    int64
	GitHubLogin string
}

type Project struct {
	ID        int64
	Name      string
	SharedEnv secret.String
}

type SealedVar struct {
	Scope string
	Owner string
	Key   string
	Value secret.String
}

type Session struct {
	ID        string
	GitHubID  int64
	ExpiresAt string
}

type Storage struct {
	Name            string
	ProjectID       int64
	Provider        string
	AccountID       string
	Endpoint        string
	AccessKeyID     string
	SecretAccessKey secret.String
	Bucket          string
	Region          string
}

type TelemetryEvent struct {
	ID        int64
	AppName   string
	Kind      string
	Level     string
	Message   secret.String
	Payload   secret.String
	CreatedAt string
}

type Volume struct {
	AppName   string
	Name      string
	MountPath string
}

type Worker struct {
	AppName string
	Name    string
	Command secret.String
	Env     secret.String
}
