// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const addVolume = `-- name: AddVolume :exec

INSERT INTO volumes (app_name, name, mount_path) VALUES (?, ?, ?)
`

type AddVolumeParams struct {
	AppName   string
	Name      string
	MountPath string
}

// Volumes
func (q *Queries) AddVolume(ctx context.Context, arg AddVolumeParams) error {
	_, err := q.db.ExecContext(ctx, addVolume, arg.AppName, arg.Name, arg.MountPath)
	return err
}

const appsUsingDatabase = `-- name: AppsUsingDatabase :many
SELECT name FROM apps WHERE linked_db = ? ORDER BY name
`

func (q *Queries) AppsUsingDatabase(ctx context.Context, linkedDb string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, appsUsingDatabase, linkedDb)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const appsUsingStorage = `-- name: AppsUsingStorage :many
SELECT name FROM apps WHERE linked_storage = ? ORDER BY name
`

func (q *Queries) AppsUsingStorage(ctx context.Context, linkedStorage string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, appsUsingStorage, linkedStorage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createApp = `-- name: CreateApp :exec

INSERT INTO apps (project_id, name, repo, port, container_port, build_path, build_strategy)
VALUES (?, ?, ?, (SELECT MAX(COALESCE(MAX(port), 8080), 8080) + 1 FROM apps), ?, ?, ?)
`

type CreateAppParams struct {
	ProjectID     int64
	Name          string
	Repo          string
	ContainerPort int64
	BuildPath     string
	BuildStrategy string
}

// Apps
// The port is the next free one for the app's proxy, starting at 8081.
func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) error {
	_, err := q.db.ExecContext(ctx, createApp,
		arg.ProjectID,
		arg.Name,
		arg.Repo,
		arg.ContainerPort,
		arg.BuildPath,
		arg.BuildStrategy,
	)
	return err
}

const createBackup = `-- name: CreateBackup :exec

INSERT INTO backups (database, object_key, size_bytes) VALUES (?, ?, ?)
`

type CreateBackupParams struct {
	Database  string
	ObjectKey string
	SizeBytes int64
}

// Backups
func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) error {
	_, err := q.db.ExecContext(ctx, createBackup, arg.Database, arg.ObjectKey, arg.SizeBytes)
	return err
}

const createDatabase = `-- name: CreateDatabase :exec

INSERT INTO databases (name, project_id, db_user, db_password) VALUES (?, ?, ?, ?)
`

type CreateDatabaseParams struct {
	Name      string
	ProjectID int64
	User      string
	Password  string
}

// Databases
func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, createDatabase,
		arg.Name,
		arg.ProjectID,
		arg.User,
		arg.Password,
	)
	return err
}

const createDeployLog = `-- name: CreateDeployLog :one

INSERT INTO deploy_logs (app_name, trigger_source, status) VALUES (?, ?, ?) RETURNING id
`

type CreateDeployLogParams struct {
	AppName string
	Trigger string
	Status  string
}

// Deploy logs
func (q *Queries) CreateDeployLog(ctx context.Context, arg CreateDeployLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDeployLog, arg.AppName, arg.Trigger, arg.Status)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createProject = `-- name: CreateProject :exec

INSERT INTO projects (name) VALUES (?)
`

// Projects
func (q *Queries) CreateProject(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createProject, name)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, github_login, expires_at) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	ID          string
	GitHubLogin string
	ExpiresAt   string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.GitHubLogin, arg.ExpiresAt)
	return err
}

const createStorage = `-- name: CreateStorage :exec

INSERT INTO storages (name, project_id, provider, account_id, endpoint, access_key_id, secret_access_key, bucket, region)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateStorageParams struct {
	Name            string
	ProjectID       int64
	Provider        string
	AccountID       string
	Endpoint        string
	AccessKeyID     string
	SecretAccessKey string
	Bucket          string
	Region          string
}

// Storages
func (q *Queries) CreateStorage(ctx context.Context, arg CreateStorageParams) error {
	_, err := q.db.ExecContext(ctx, createStorage,
		arg.Name,
		arg.ProjectID,
		arg.Provider,
		arg.AccountID,
		arg.Endpoint,
		arg.AccessKeyID,
		arg.SecretAccessKey,
		arg.Bucket,
		arg.Region,
	)
	return err
}

const createTelemetryEvent = `-- name: CreateTelemetryEvent :exec

INSERT INTO telemetry_events (app_name, kind, level, message, payload) VALUES (?, ?, ?, ?, ?)
`

type CreateTelemetryEventParams struct {
	AppName string
	Kind    string
	Level   string
	Message string
	Payload string
}

// Telemetry
func (q *Queries) CreateTelemetryEvent(ctx context.Context, arg CreateTelemetryEventParams) error {
	_, err := q.db.ExecContext(ctx, createTelemetryEvent,
		arg.AppName,
		arg.Kind,
		arg.Level,
		arg.Message,
		arg.Payload,
	)
	return err
}

const databasesBackingUpTo = `-- name: DatabasesBackingUpTo :many
SELECT name FROM databases WHERE backup_storage = ? ORDER BY name
`

func (q *Queries) DatabasesBackingUpTo(ctx context.Context, backupStorage string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, databasesBackingUpTo, backupStorage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps WHERE name = ?
`

func (q *Queries) DeleteApp(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteApp, name)
	return err
}

const deleteDatabase = `-- name: DeleteDatabase :exec
DELETE FROM databases WHERE name = ?
`

func (q *Queries) DeleteDatabase(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteDatabase, name)
	return err
}

const deleteDeployLogsOfApp = `-- name: DeleteDeployLogsOfApp :exec
DELETE FROM deploy_logs WHERE app_name = ?
`

func (q *Queries) DeleteDeployLogsOfApp(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteDeployLogsOfApp, appName)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE name = ?
`

func (q *Queries) DeleteProject(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, name)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteStorage = `-- name: DeleteStorage :exec
DELETE FROM storages WHERE name = ?
`

func (q *Queries) DeleteStorage(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteStorage, name)
	return err
}

const deleteTelemetryOfApp = `-- name: DeleteTelemetryOfApp :exec
DELETE FROM telemetry_events WHERE app_name = ?
`

func (q *Queries) DeleteTelemetryOfApp(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteTelemetryOfApp, appName)
	return err
}

const deleteVolume = `-- name: DeleteVolume :exec
DELETE FROM volumes WHERE app_name = ? AND name = ?
`

type DeleteVolumeParams struct {
	AppName string
	Name    string
}

func (q *Queries) DeleteVolume(ctx context.Context, arg DeleteVolumeParams) error {
	_, err := q.db.ExecContext(ctx, deleteVolume, arg.AppName, arg.Name)
	return err
}

const deleteVolumesOfApp = `-- name: DeleteVolumesOfApp :exec
DELETE FROM volumes WHERE app_name = ?
`

func (q *Queries) DeleteVolumesOfApp(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteVolumesOfApp, appName)
	return err
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM workers WHERE app_name = ?
`

func (q *Queries) DeleteWorker(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteWorker, appName)
	return err
}

const failRunningDeployLogs = `-- name: FailRunningDeployLogs :exec
UPDATE deploy_logs SET status = 'failed', output = output || char(10) || 'interrupted: agent restarted' WHERE status = 'running'
`

func (q *Queries) FailRunningDeployLogs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, failRunningDeployLogs)
	return err
}

const getAccessControl = `-- name: GetAccessControl :one
SELECT id, owner_login, allowed_logins FROM access_control WHERE id = 1
`

func (q *Queries) GetAccessControl(ctx context.Context) (AccessControl, error) {
	row := q.db.QueryRowContext(ctx, getAccessControl)
	var i AccessControl
	err := row.Scan(&i.ID, &i.OwnerLogin, &i.AllowedLogins)
	return i, err
}

const getApp = `-- name: GetApp :one
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes FROM app_view WHERE name = ?
`

func (q *Queries) GetApp(ctx context.Context, name string) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectName,
		&i.Name,
		&i.Repo,
		&i.Domain,
		&i.DnsZoneID,
		&i.DnsRecordID,
		&i.Port,
		&i.ContainerPort,
		&i.LivePort,
		&i.BuildPath,
		&i.BuildStrategy,
		&i.ActiveSlot,
		&i.Env,
		&i.SentryKey,
		&i.HealthCheckPath,
		&i.LinkedDB,
		&i.LinkedStorage,
		&i.ShareVolumes,
	)
	return i, err
}

const getAppByDomain = `-- name: GetAppByDomain :one
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes FROM app_view WHERE domain = ? AND domain != ''
`

func (q *Queries) GetAppByDomain(ctx context.Context, domain string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByDomain, domain)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectName,
		&i.Name,
		&i.Repo,
		&i.Domain,
		&i.DnsZoneID,
		&i.DnsRecordID,
		&i.Port,
		&i.ContainerPort,
		&i.LivePort,
		&i.BuildPath,
		&i.BuildStrategy,
		&i.ActiveSlot,
		&i.Env,
		&i.SentryKey,
		&i.HealthCheckPath,
		&i.LinkedDB,
		&i.LinkedStorage,
		&i.ShareVolumes,
	)
	return i, err
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes FROM app_view WHERE id = ?
`

func (q *Queries) GetAppByID(ctx context.Context, id int64) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectName,
		&i.Name,
		&i.Repo,
		&i.Domain,
		&i.DnsZoneID,
		&i.DnsRecordID,
		&i.Port,
		&i.ContainerPort,
		&i.LivePort,
		&i.BuildPath,
		&i.BuildStrategy,
		&i.ActiveSlot,
		&i.Env,
		&i.SentryKey,
		&i.HealthCheckPath,
		&i.LinkedDB,
		&i.LinkedStorage,
		&i.ShareVolumes,
	)
	return i, err
}

const getCloudflare = `-- name: GetCloudflare :one

SELECT id, access_token, refresh_token, expires_at, account_id, tunnel_id, tunnel_token, panel_zone_id, panel_record_id FROM cloudflare WHERE id = 1
`

// Cloudflare
func (q *Queries) GetCloudflare(ctx context.Context) (Cloudflare, error) {
	row := q.db.QueryRowContext(ctx, getCloudflare)
	var i Cloudflare
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.AccountID,
		&i.TunnelID,
		&i.TunnelToken,
		&i.PanelZoneID,
		&i.PanelRecordID,
	)
	return i, err
}

const getDatabase = `-- name: GetDatabase :one
SELECT name, project_id, db_user, db_password, backup_storage FROM databases WHERE name = ?
`

func (q *Queries) GetDatabase(ctx context.Context, name string) (Database, error) {
	row := q.db.QueryRowContext(ctx, getDatabase, name)
	var i Database
	err := row.Scan(
		&i.Name,
		&i.ProjectID,
		&i.User,
		&i.Password,
		&i.BackupStorage,
	)
	return i, err
}

const getGitHubApp = `-- name: GetGitHubApp :one
SELECT id, app_id, slug, private_key, webhook_secret, client_id, client_secret FROM github_app WHERE id = 1
`

func (q *Queries) GetGitHubApp(ctx context.Context) (GitHubApp, error) {
	row := q.db.QueryRowContext(ctx, getGitHubApp)
	var i GitHubApp
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Slug,
		&i.PrivateKey,
		&i.WebhookSecret,
		&i.ClientID,
		&i.ClientSecret,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, shared_env FROM projects WHERE name = ?
`

func (q *Queries) GetProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, name)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.SharedEnv)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, shared_env FROM projects WHERE id = ?
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.SharedEnv)
	return i, err
}

const getSessionRow = `-- name: GetSessionRow :one
SELECT id, github_login, expires_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSessionRow(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionRow, id)
	var i Session
	err := row.Scan(&i.ID, &i.GitHubLogin, &i.ExpiresAt)
	return i, err
}

const getStorage = `-- name: GetStorage :one
SELECT name, project_id, provider, account_id, endpoint, access_key_id, secret_access_key, bucket, region FROM storages WHERE name = ?
`

func (q *Queries) GetStorage(ctx context.Context, name string) (Storage, error) {
	row := q.db.QueryRowContext(ctx, getStorage, name)
	var i Storage
	err := row.Scan(
		&i.Name,
		&i.ProjectID,
		&i.Provider,
		&i.AccountID,
		&i.Endpoint,
		&i.AccessKeyID,
		&i.SecretAccessKey,
		&i.Bucket,
		&i.Region,
	)
	return i, err
}

const getWorker = `-- name: GetWorker :one
SELECT app_name, name, command, env FROM workers WHERE app_name = ?
`

func (q *Queries) GetWorker(ctx context.Context, appName string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorker, appName)
	var i Worker
	err := row.Scan(
		&i.AppName,
		&i.Name,
		&i.Command,
		&i.Env,
	)
	return i, err
}

const listAllVolumes = `-- name: ListAllVolumes :many
SELECT app_name, name, mount_path FROM volumes
`

func (q *Queries) ListAllVolumes(ctx context.Context) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listAllVolumes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(&i.AppName, &i.Name, &i.MountPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApps = `-- name: ListApps :many
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes FROM app_view ORDER BY name
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Name,
			&i.Repo,
			&i.Domain,
			&i.DnsZoneID,
			&i.DnsRecordID,
			&i.Port,
			&i.ContainerPort,
			&i.LivePort,
			&i.BuildPath,
			&i.BuildStrategy,
			&i.ActiveSlot,
			&i.Env,
			&i.SentryKey,
			&i.HealthCheckPath,
			&i.LinkedDB,
			&i.LinkedStorage,
			&i.ShareVolumes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByProject = `-- name: ListAppsByProject :many
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes FROM app_view WHERE project_id = ? ORDER BY name
`

func (q *Queries) ListAppsByProject(ctx context.Context, projectID int64) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Name,
			&i.Repo,
			&i.Domain,
			&i.DnsZoneID,
			&i.DnsRecordID,
			&i.Port,
			&i.ContainerPort,
			&i.LivePort,
			&i.BuildPath,
			&i.BuildStrategy,
			&i.ActiveSlot,
			&i.Env,
			&i.SentryKey,
			&i.HealthCheckPath,
			&i.LinkedDB,
			&i.LinkedStorage,
			&i.ShareVolumes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByRepo = `-- name: ListAppsByRepo :many
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes FROM app_view WHERE repo = ?
`

func (q *Queries) ListAppsByRepo(ctx context.Context, repo string) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByRepo, repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Name,
			&i.Repo,
			&i.Domain,
			&i.DnsZoneID,
			&i.DnsRecordID,
			&i.Port,
			&i.ContainerPort,
			&i.LivePort,
			&i.BuildPath,
			&i.BuildStrategy,
			&i.ActiveSlot,
			&i.Env,
			&i.SentryKey,
			&i.HealthCheckPath,
			&i.LinkedDB,
			&i.LinkedStorage,
			&i.ShareVolumes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackups = `-- name: ListBackups :many
SELECT id, "database", object_key, size_bytes, created_at FROM backups WHERE database = ? ORDER BY id DESC LIMIT ?
`

type ListBackupsParams struct {
	Database string
	Limit    int64
}

func (q *Queries) ListBackups(ctx context.Context, arg ListBackupsParams) ([]Backup, error) {
	rows, err := q.db.QueryContext(ctx, listBackups, arg.Database, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backup
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.Database,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabases = `-- name: ListDatabases :many
SELECT name, project_id, db_user, db_password, backup_storage FROM databases ORDER BY name
`

func (q *Queries) ListDatabases(ctx context.Context) ([]Database, error) {
	rows, err := q.db.QueryContext(ctx, listDatabases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Database
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.Name,
			&i.ProjectID,
			&i.User,
			&i.Password,
			&i.BackupStorage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByProject = `-- name: ListDatabasesByProject :many
SELECT name, project_id, db_user, db_password, backup_storage FROM databases WHERE project_id = ? ORDER BY name
`

func (q *Queries) ListDatabasesByProject(ctx context.Context, projectID int64) ([]Database, error) {
	rows, err := q.db.QueryContext(ctx, listDatabasesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Database
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.Name,
			&i.ProjectID,
			&i.User,
			&i.Password,
			&i.BackupStorage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployLogs = `-- name: ListDeployLogs :many
SELECT id, app_name, trigger_source, status, output, created_at FROM deploy_logs WHERE app_name = ? ORDER BY id DESC LIMIT ?
`

type ListDeployLogsParams struct {
	AppName string
	Limit   int64
}

func (q *Queries) ListDeployLogs(ctx context.Context, arg ListDeployLogsParams) ([]DeployLog, error) {
	rows, err := q.db.QueryContext(ctx, listDeployLogs, arg.AppName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeployLog
	for rows.Next() {
		var i DeployLog
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.Trigger,
			&i.Status,
			&i.Output,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, shared_env FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ID, &i.Name, &i.SharedEnv); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoragesByProject = `-- name: ListStoragesByProject :many
SELECT name, project_id, provider, account_id, endpoint, access_key_id, secret_access_key, bucket, region FROM storages WHERE project_id = ? ORDER BY name
`

func (q *Queries) ListStoragesByProject(ctx context.Context, projectID int64) ([]Storage, error) {
	rows, err := q.db.QueryContext(ctx, listStoragesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Storage
	for rows.Next() {
		var i Storage
		if err := rows.Scan(
			&i.Name,
			&i.ProjectID,
			&i.Provider,
			&i.AccountID,
			&i.Endpoint,
			&i.AccessKeyID,
			&i.SecretAccessKey,
			&i.Bucket,
			&i.Region,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTelemetryEvents = `-- name: ListTelemetryEvents :many
SELECT id, app_name, kind, level, message, payload, created_at FROM telemetry_events WHERE app_name = ? ORDER BY id DESC LIMIT ?
`

type ListTelemetryEventsParams struct {
	AppName string
	Limit   int64
}

func (q *Queries) ListTelemetryEvents(ctx context.Context, arg ListTelemetryEventsParams) ([]TelemetryEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTelemetryEvents, arg.AppName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemetryEvent
	for rows.Next() {
		var i TelemetryEvent
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.Kind,
			&i.Level,
			&i.Message,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumes = `-- name: ListVolumes :many
SELECT app_name, name, mount_path FROM volumes WHERE app_name = ? ORDER BY name
`

func (q *Queries) ListVolumes(ctx context.Context, appName string) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listVolumes, appName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(&i.AppName, &i.Name, &i.MountPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDeployLogs = `-- name: PruneDeployLogs :exec
DELETE FROM deploy_logs WHERE created_at < ?
`

func (q *Queries) PruneDeployLogs(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, pruneDeployLogs, createdAt)
	return err
}

const pruneTelemetry = `-- name: PruneTelemetry :exec
DELETE FROM telemetry_events WHERE created_at < ?
`

func (q *Queries) PruneTelemetry(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, pruneTelemetry, createdAt)
	return err
}

const saveCloudflareToken = `-- name: SaveCloudflareToken :exec
INSERT INTO cloudflare (id, access_token, refresh_token, expires_at) VALUES (1, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET access_token = excluded.access_token, refresh_token = excluded.refresh_token, expires_at = excluded.expires_at
`

type SaveCloudflareTokenParams struct {
	AccessToken  string
	RefreshToken string
	ExpiresAt    string
}

func (q *Queries) SaveCloudflareToken(ctx context.Context, arg SaveCloudflareTokenParams) error {
	_, err := q.db.ExecContext(ctx, saveCloudflareToken, arg.AccessToken, arg.RefreshToken, arg.ExpiresAt)
	return err
}

const saveCloudflareTunnel = `-- name: SaveCloudflareTunnel :exec
UPDATE cloudflare SET account_id = ?, tunnel_id = ?, tunnel_token = ?, panel_zone_id = ?, panel_record_id = ? WHERE id = 1
`

type SaveCloudflareTunnelParams struct {
	AccountID     string
	TunnelID      string
	TunnelToken   string
	PanelZoneID   string
	PanelRecordID string
}

func (q *Queries) SaveCloudflareTunnel(ctx context.Context, arg SaveCloudflareTunnelParams) error {
	_, err := q.db.ExecContext(ctx, saveCloudflareTunnel,
		arg.AccountID,
		arg.TunnelID,
		arg.TunnelToken,
		arg.PanelZoneID,
		arg.PanelRecordID,
	)
	return err
}

const saveGitHubApp = `-- name: SaveGitHubApp :exec

INSERT OR REPLACE INTO github_app (id, app_id, slug, private_key, webhook_secret, client_id, client_secret)
VALUES (1, ?, ?, ?, ?, ?, ?)
`

type SaveGitHubAppParams struct {
	AppID         int64
	Slug          string
	PrivateKey    string
	WebhookSecret string
	ClientID      string
	ClientSecret  string
}

// GitHub App and access control
func (q *Queries) SaveGitHubApp(ctx context.Context, arg SaveGitHubAppParams) error {
	_, err := q.db.ExecContext(ctx, saveGitHubApp,
		arg.AppID,
		arg.Slug,
		arg.PrivateKey,
		arg.WebhookSecret,
		arg.ClientID,
		arg.ClientSecret,
	)
	return err
}

const saveWorker = `-- name: SaveWorker :exec

INSERT INTO workers (app_name, name, command, env) VALUES (?, ?, ?, ?)
ON CONFLICT(app_name) DO UPDATE SET name = excluded.name, command = excluded.command, env = excluded.env
`

type SaveWorkerParams struct {
	AppName string
	Name    string
	Command string
	Env     string
}

// Workers
func (q *Queries) SaveWorker(ctx context.Context, arg SaveWorkerParams) error {
	_, err := q.db.ExecContext(ctx, saveWorker,
		arg.AppName,
		arg.Name,
		arg.Command,
		arg.Env,
	)
	return err
}

const setAllowedLogins = `-- name: SetAllowedLogins :exec
INSERT INTO access_control (id, allowed_logins) VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET allowed_logins = excluded.allowed_logins
`

func (q *Queries) SetAllowedLogins(ctx context.Context, allowedLogins string) error {
	_, err := q.db.ExecContext(ctx, setAllowedLogins, allowedLogins)
	return err
}

const setAppDomain = `-- name: SetAppDomain :exec
UPDATE apps SET domain = ?, dns_zone_id = ?, dns_record_id = ? WHERE name = ?
`

type SetAppDomainParams struct {
	Domain      string
	DnsZoneID   string
	DnsRecordID string
	Name        string
}

func (q *Queries) SetAppDomain(ctx context.Context, arg SetAppDomainParams) error {
	_, err := q.db.ExecContext(ctx, setAppDomain,
		arg.Domain,
		arg.DnsZoneID,
		arg.DnsRecordID,
		arg.Name,
	)
	return err
}

const setAppEnv = `-- name: SetAppEnv :exec
UPDATE apps SET env = ? WHERE name = ?
`

type SetAppEnvParams struct {
	Env  string
	Name string
}

func (q *Queries) SetAppEnv(ctx context.Context, arg SetAppEnvParams) error {
	_, err := q.db.ExecContext(ctx, setAppEnv, arg.Env, arg.Name)
	return err
}

const setAppLinkedDB = `-- name: SetAppLinkedDB :exec
UPDATE apps SET linked_db = ? WHERE name = ?
`

type SetAppLinkedDBParams struct {
	LinkedDB string
	Name     string
}

func (q *Queries) SetAppLinkedDB(ctx context.Context, arg SetAppLinkedDBParams) error {
	_, err := q.db.ExecContext(ctx, setAppLinkedDB, arg.LinkedDB, arg.Name)
	return err
}

const setAppLinkedStorage = `-- name: SetAppLinkedStorage :exec
UPDATE apps SET linked_storage = ? WHERE name = ?
`

type SetAppLinkedStorageParams struct {
	LinkedStorage string
	Name          string
}

func (q *Queries) SetAppLinkedStorage(ctx context.Context, arg SetAppLinkedStorageParams) error {
	_, err := q.db.ExecContext(ctx, setAppLinkedStorage, arg.LinkedStorage, arg.Name)
	return err
}

const setAppLive = `-- name: SetAppLive :exec
UPDATE apps SET active_slot = ?, live_port = ? WHERE name = ?
`

type SetAppLiveParams struct {
	ActiveSlot string
	LivePort   int64
	Name       string
}

func (q *Queries) SetAppLive(ctx context.Context, arg SetAppLiveParams) error {
	_, err := q.db.ExecContext(ctx, setAppLive, arg.ActiveSlot, arg.LivePort, arg.Name)
	return err
}

const setAppSentryKey = `-- name: SetAppSentryKey :exec
UPDATE apps SET sentry_key = ? WHERE name = ?
`

type SetAppSentryKeyParams struct {
	SentryKey string
	Name      string
}

func (q *Queries) SetAppSentryKey(ctx context.Context, arg SetAppSentryKeyParams) error {
	_, err := q.db.ExecContext(ctx, setAppSentryKey, arg.SentryKey, arg.Name)
	return err
}

const setAppSettings = `-- name: SetAppSettings :exec
UPDATE apps SET container_port = ?, health_check_path = ? WHERE name = ?
`

type SetAppSettingsParams struct {
	ContainerPort   int64
	HealthCheckPath string
	Name            string
}

func (q *Queries) SetAppSettings(ctx context.Context, arg SetAppSettingsParams) error {
	_, err := q.db.ExecContext(ctx, setAppSettings, arg.ContainerPort, arg.HealthCheckPath, arg.Name)
	return err
}

const setAppShareVolumes = `-- name: SetAppShareVolumes :exec
UPDATE apps SET share_volumes = ? WHERE name = ?
`

type SetAppShareVolumesParams struct {
	ShareVolumes int64
	Name         string
}

func (q *Queries) SetAppShareVolumes(ctx context.Context, arg SetAppShareVolumesParams) error {
	_, err := q.db.ExecContext(ctx, setAppShareVolumes, arg.ShareVolumes, arg.Name)
	return err
}

const setDatabaseBackupStorage = `-- name: SetDatabaseBackupStorage :exec
UPDATE databases SET backup_storage = ? WHERE name = ?
`

type SetDatabaseBackupStorageParams struct {
	BackupStorage string
	Name          string
}

func (q *Queries) SetDatabaseBackupStorage(ctx context.Context, arg SetDatabaseBackupStorageParams) error {
	_, err := q.db.ExecContext(ctx, setDatabaseBackupStorage, arg.BackupStorage, arg.Name)
	return err
}

const setOwner = `-- name: SetOwner :exec
INSERT INTO access_control (id, owner_login) VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET owner_login = excluded.owner_login
`

func (q *Queries) SetOwner(ctx context.Context, ownerLogin string) error {
	_, err := q.db.ExecContext(ctx, setOwner, ownerLogin)
	return err
}

const setProjectSharedEnv = `-- name: SetProjectSharedEnv :exec
UPDATE projects SET shared_env = ? WHERE name = ?
`

type SetProjectSharedEnvParams struct {
	SharedEnv string
	Name      string
}

func (q *Queries) SetProjectSharedEnv(ctx context.Context, arg SetProjectSharedEnvParams) error {
	_, err := q.db.ExecContext(ctx, setProjectSharedEnv, arg.SharedEnv, arg.Name)
	return err
}

const updateDeployLog = `-- name: UpdateDeployLog :exec
UPDATE deploy_logs SET status = ?, output = ? WHERE id = ?
`

type UpdateDeployLogParams struct {
	Status string
	Output string
	ID     int64
}

func (q *Queries) UpdateDeployLog(ctx context.Context, arg UpdateDeployLogParams) error {
	_, err := q.db.ExecContext(ctx, updateDeployLog, arg.Status, arg.Output, arg.ID)
	return err
}
