// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/x0ryz/hakobu/internal/secret"
)

const addVolume = `-- name: AddVolume :exec

INSERT INTO volumes (app_name, name, mount_path) VALUES (?, ?, ?)
`

type AddVolumeParams struct {
	AppName   string
	Name      string
	MountPath string
}

// Volumes
func (q *Queries) AddVolume(ctx context.Context, arg AddVolumeParams) error {
	_, err := q.db.ExecContext(ctx, addVolume, arg.AppName, arg.Name, arg.MountPath)
	return err
}

const appsUsingDatabase = `-- name: AppsUsingDatabase :many
SELECT name FROM apps WHERE linked_db = ? ORDER BY name
`

func (q *Queries) AppsUsingDatabase(ctx context.Context, linkedDb string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, appsUsingDatabase, linkedDb)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const appsUsingStorage = `-- name: AppsUsingStorage :many
SELECT name FROM apps WHERE linked_storage = ? ORDER BY name
`

func (q *Queries) AppsUsingStorage(ctx context.Context, linkedStorage string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, appsUsingStorage, linkedStorage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOAuthClients = `-- name: CountOAuthClients :one
SELECT COUNT(*) FROM oauth_clients
`

func (q *Queries) CountOAuthClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOAuthClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApp = `-- name: CreateApp :exec

INSERT INTO apps (project_id, name, repo, port, container_port, build_path, build_strategy)
VALUES (?, ?, ?, (SELECT MAX(COALESCE(MAX(port), 8080), 8080) + 1 FROM apps), ?, ?, ?)
`

type CreateAppParams struct {
	ProjectID     int64
	Name          string
	Repo          string
	ContainerPort int64
	BuildPath     string
	BuildStrategy string
}

// Apps
// The port is the next free one for the app's proxy, starting at 8081.
func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) error {
	_, err := q.db.ExecContext(ctx, createApp,
		arg.ProjectID,
		arg.Name,
		arg.Repo,
		arg.ContainerPort,
		arg.BuildPath,
		arg.BuildStrategy,
	)
	return err
}

const createBackup = `-- name: CreateBackup :one

INSERT INTO backups (database, object_key, parts, size_bytes, sha256, file_key) VALUES (?, ?, ?, ?, ?, ?) RETURNING id
`

type CreateBackupParams struct {
	Database  string
	ObjectKey string
	Parts     int64
	SizeBytes int64
	SHA256    string
	FileKey   secret.String
}

// Backups
func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createBackup,
		arg.Database,
		arg.ObjectKey,
		arg.Parts,
		arg.SizeBytes,
		arg.SHA256,
		arg.FileKey,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createDatabase = `-- name: CreateDatabase :exec

INSERT INTO databases (name, project_id, db_user, db_password) VALUES (?, ?, ?, ?)
`

type CreateDatabaseParams struct {
	Name      string
	ProjectID int64
	User      string
	Password  secret.String
}

// Databases
func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, createDatabase,
		arg.Name,
		arg.ProjectID,
		arg.User,
		arg.Password,
	)
	return err
}

const createDeployLog = `-- name: CreateDeployLog :one

INSERT INTO deploy_logs (app_name, trigger_source, status) VALUES (?, ?, ?) RETURNING id
`

type CreateDeployLogParams struct {
	AppName string
	Trigger string
	Status  string
}

// Deploy logs
func (q *Queries) CreateDeployLog(ctx context.Context, arg CreateDeployLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDeployLog, arg.AppName, arg.Trigger, arg.Status)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOAuthClient = `-- name: CreateOAuthClient :exec

INSERT INTO oauth_clients (id, name, redirect_uris) VALUES (?, ?, ?)
`

type CreateOAuthClientParams struct {
	ID           string
	Name         string
	RedirectURIs string
}

// OAuth (MCP clients)
func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthClient, arg.ID, arg.Name, arg.RedirectURIs)
	return err
}

const createOAuthGrant = `-- name: CreateOAuthGrant :one
INSERT INTO oauth_grants (client_id, client_name, redirect_uri, scope, github_id) VALUES (?, ?, ?, ?, ?) RETURNING id
`

type CreateOAuthGrantParams struct {
	ClientID    string
	ClientName  string
	RedirectURI string
	Scope       string
	GitHubID    int64
}

func (q *Queries) CreateOAuthGrant(ctx context.Context, arg CreateOAuthGrantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOAuthGrant,
		arg.ClientID,
		arg.ClientName,
		arg.RedirectURI,
		arg.Scope,
		arg.GitHubID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOAuthToken = `-- name: CreateOAuthToken :exec
INSERT INTO oauth_tokens (id, grant_id, kind, code_challenge, expires_at) VALUES (?, ?, ?, ?, ?)
`

type CreateOAuthTokenParams struct {
	ID            string
	GrantID       int64
	Kind          string
	CodeChallenge string
	ExpiresAt     string
}

func (q *Queries) CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthToken,
		arg.ID,
		arg.GrantID,
		arg.Kind,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
	return err
}

const createProject = `-- name: CreateProject :exec

INSERT INTO projects (name) VALUES (?)
`

// Projects
func (q *Queries) CreateProject(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createProject, name)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, github_id, signed_in_at, expires_at) VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID         string
	GitHubID   int64
	SignedInAt string
	ExpiresAt  string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.GitHubID,
		arg.SignedInAt,
		arg.ExpiresAt,
	)
	return err
}

const createStorage = `-- name: CreateStorage :exec

INSERT INTO storages (name, project_id, provider, account_id, endpoint, access_key_id, secret_access_key, bucket, region)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateStorageParams struct {
	Name            string
	ProjectID       int64
	Provider        string
	AccountID       string
	Endpoint        string
	AccessKeyID     string
	SecretAccessKey secret.String
	Bucket          string
	Region          string
}

// Storages
func (q *Queries) CreateStorage(ctx context.Context, arg CreateStorageParams) error {
	_, err := q.db.ExecContext(ctx, createStorage,
		arg.Name,
		arg.ProjectID,
		arg.Provider,
		arg.AccountID,
		arg.Endpoint,
		arg.AccessKeyID,
		arg.SecretAccessKey,
		arg.Bucket,
		arg.Region,
	)
	return err
}

const createVolumeBackup = `-- name: CreateVolumeBackup :one
INSERT INTO volume_backups (app_name, volume, object_key, parts, size_bytes, sha256, file_key) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type CreateVolumeBackupParams struct {
	AppName   string
	Volume    string
	ObjectKey string
	Parts     int64
	SizeBytes int64
	SHA256    string
	FileKey   secret.String
}

func (q *Queries) CreateVolumeBackup(ctx context.Context, arg CreateVolumeBackupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createVolumeBackup,
		arg.AppName,
		arg.Volume,
		arg.ObjectKey,
		arg.Parts,
		arg.SizeBytes,
		arg.SHA256,
		arg.FileKey,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAllOAuthGrants = `-- name: DeleteAllOAuthGrants :exec
DELETE FROM oauth_grants
`

func (q *Queries) DeleteAllOAuthGrants(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllOAuthGrants)
	return err
}

const deleteAllSessions = `-- name: DeleteAllSessions :exec
DELETE FROM sessions
`

func (q *Queries) DeleteAllSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessions)
	return err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps WHERE name = ?
`

func (q *Queries) DeleteApp(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteApp, name)
	return err
}

const deleteBackup = `-- name: DeleteBackup :exec
DELETE FROM backups WHERE id = ?
`

func (q *Queries) DeleteBackup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBackup, id)
	return err
}

const deleteBackupsOf = `-- name: DeleteBackupsOf :exec
DELETE FROM backups WHERE database = ?
`

func (q *Queries) DeleteBackupsOf(ctx context.Context, database string) error {
	_, err := q.db.ExecContext(ctx, deleteBackupsOf, database)
	return err
}

const deleteDatabase = `-- name: DeleteDatabase :exec
DELETE FROM databases WHERE name = ?
`

func (q *Queries) DeleteDatabase(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteDatabase, name)
	return err
}

const deleteDeployLogsOfApp = `-- name: DeleteDeployLogsOfApp :exec
DELETE FROM deploy_logs WHERE app_name = ?
`

func (q *Queries) DeleteDeployLogsOfApp(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteDeployLogsOfApp, appName)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteNotify = `-- name: DeleteNotify :exec
DELETE FROM notify WHERE id = 1
`

func (q *Queries) DeleteNotify(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteNotify)
	return err
}

const deleteOAuthGrant = `-- name: DeleteOAuthGrant :exec
DELETE FROM oauth_grants WHERE id = ?
`

func (q *Queries) DeleteOAuthGrant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthGrant, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE name = ?
`

func (q *Queries) DeleteProject(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, name)
	return err
}

const deleteSealedVar = `-- name: DeleteSealedVar :exec
DELETE FROM sealed_vars WHERE scope = ? AND owner = ? AND key = ?
`

type DeleteSealedVarParams struct {
	Scope string
	Owner string
	Key   string
}

func (q *Queries) DeleteSealedVar(ctx context.Context, arg DeleteSealedVarParams) error {
	_, err := q.db.ExecContext(ctx, deleteSealedVar, arg.Scope, arg.Owner, arg.Key)
	return err
}

const deleteSealedVarsOf = `-- name: DeleteSealedVarsOf :exec
DELETE FROM sealed_vars WHERE scope = ? AND owner = ?
`

type DeleteSealedVarsOfParams struct {
	Scope string
	Owner string
}

func (q *Queries) DeleteSealedVarsOf(ctx context.Context, arg DeleteSealedVarsOfParams) error {
	_, err := q.db.ExecContext(ctx, deleteSealedVarsOf, arg.Scope, arg.Owner)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteStorage = `-- name: DeleteStorage :exec
DELETE FROM storages WHERE name = ?
`

func (q *Queries) DeleteStorage(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteStorage, name)
	return err
}

const deleteVolume = `-- name: DeleteVolume :exec
DELETE FROM volumes WHERE app_name = ? AND name = ?
`

type DeleteVolumeParams struct {
	AppName string
	Name    string
}

func (q *Queries) DeleteVolume(ctx context.Context, arg DeleteVolumeParams) error {
	_, err := q.db.ExecContext(ctx, deleteVolume, arg.AppName, arg.Name)
	return err
}

const deleteVolumeBackup = `-- name: DeleteVolumeBackup :exec
DELETE FROM volume_backups WHERE id = ?
`

func (q *Queries) DeleteVolumeBackup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVolumeBackup, id)
	return err
}

const deleteVolumeBackupsOf = `-- name: DeleteVolumeBackupsOf :exec
DELETE FROM volume_backups WHERE app_name = ? AND volume = ?
`

type DeleteVolumeBackupsOfParams struct {
	AppName string
	Volume  string
}

func (q *Queries) DeleteVolumeBackupsOf(ctx context.Context, arg DeleteVolumeBackupsOfParams) error {
	_, err := q.db.ExecContext(ctx, deleteVolumeBackupsOf, arg.AppName, arg.Volume)
	return err
}

const deleteVolumeBackupsOfApp = `-- name: DeleteVolumeBackupsOfApp :exec
DELETE FROM volume_backups WHERE app_name = ?
`

func (q *Queries) DeleteVolumeBackupsOfApp(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteVolumeBackupsOfApp, appName)
	return err
}

const deleteVolumesOfApp = `-- name: DeleteVolumesOfApp :exec
DELETE FROM volumes WHERE app_name = ?
`

func (q *Queries) DeleteVolumesOfApp(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteVolumesOfApp, appName)
	return err
}

const deleteWatchdog = `-- name: DeleteWatchdog :exec
DELETE FROM watchdog
`

func (q *Queries) DeleteWatchdog(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteWatchdog)
	return err
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM workers WHERE app_name = ?
`

func (q *Queries) DeleteWorker(ctx context.Context, appName string) error {
	_, err := q.db.ExecContext(ctx, deleteWorker, appName)
	return err
}

const getApp = `-- name: GetApp :one
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes, memory_mb, cpus, snapshot_db, snapshot_at FROM app_view WHERE name = ?
`

func (q *Queries) GetApp(ctx context.Context, name string) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectName,
		&i.Name,
		&i.Repo,
		&i.Domain,
		&i.DnsZoneID,
		&i.DnsRecordID,
		&i.Port,
		&i.ContainerPort,
		&i.LivePort,
		&i.BuildPath,
		&i.BuildStrategy,
		&i.ActiveSlot,
		&i.Env,
		&i.SentryKey,
		&i.HealthCheckPath,
		&i.LinkedDB,
		&i.LinkedStorage,
		&i.ShareVolumes,
		&i.MemoryMB,
		&i.Cpus,
		&i.SnapshotDB,
		&i.SnapshotAt,
	)
	return i, err
}

const getAppByDomain = `-- name: GetAppByDomain :one
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes, memory_mb, cpus, snapshot_db, snapshot_at FROM app_view WHERE domain = ? AND domain != ''
`

func (q *Queries) GetAppByDomain(ctx context.Context, domain string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByDomain, domain)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectName,
		&i.Name,
		&i.Repo,
		&i.Domain,
		&i.DnsZoneID,
		&i.DnsRecordID,
		&i.Port,
		&i.ContainerPort,
		&i.LivePort,
		&i.BuildPath,
		&i.BuildStrategy,
		&i.ActiveSlot,
		&i.Env,
		&i.SentryKey,
		&i.HealthCheckPath,
		&i.LinkedDB,
		&i.LinkedStorage,
		&i.ShareVolumes,
		&i.MemoryMB,
		&i.Cpus,
		&i.SnapshotDB,
		&i.SnapshotAt,
	)
	return i, err
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes, memory_mb, cpus, snapshot_db, snapshot_at FROM app_view WHERE id = ?
`

func (q *Queries) GetAppByID(ctx context.Context, id int64) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectName,
		&i.Name,
		&i.Repo,
		&i.Domain,
		&i.DnsZoneID,
		&i.DnsRecordID,
		&i.Port,
		&i.ContainerPort,
		&i.LivePort,
		&i.BuildPath,
		&i.BuildStrategy,
		&i.ActiveSlot,
		&i.Env,
		&i.SentryKey,
		&i.HealthCheckPath,
		&i.LinkedDB,
		&i.LinkedStorage,
		&i.ShareVolumes,
		&i.MemoryMB,
		&i.Cpus,
		&i.SnapshotDB,
		&i.SnapshotAt,
	)
	return i, err
}

const getBackup = `-- name: GetBackup :one
SELECT id, "database", object_key, parts, size_bytes, sha256, created_at, verified_at, verify_error, tables, file_key FROM backups WHERE id = ?
`

func (q *Queries) GetBackup(ctx context.Context, id int64) (Backup, error) {
	row := q.db.QueryRowContext(ctx, getBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.Database,
		&i.ObjectKey,
		&i.Parts,
		&i.SizeBytes,
		&i.SHA256,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.VerifyError,
		&i.Tables,
		&i.FileKey,
	)
	return i, err
}

const getCloudflare = `-- name: GetCloudflare :one

SELECT id, api_token, account_id, tunnel_id, tunnel_token, panel_zone_id, panel_record_id, backup_bucket FROM cloudflare WHERE id = 1
`

// Cloudflare
func (q *Queries) GetCloudflare(ctx context.Context) (Cloudflare, error) {
	row := q.db.QueryRowContext(ctx, getCloudflare)
	var i Cloudflare
	err := row.Scan(
		&i.ID,
		&i.ApiToken,
		&i.AccountID,
		&i.TunnelID,
		&i.TunnelToken,
		&i.PanelZoneID,
		&i.PanelRecordID,
		&i.BackupBucket,
	)
	return i, err
}

const getDatabase = `-- name: GetDatabase :one
SELECT name, project_id, db_user, db_password FROM databases WHERE name = ?
`

func (q *Queries) GetDatabase(ctx context.Context, name string) (Database, error) {
	row := q.db.QueryRowContext(ctx, getDatabase, name)
	var i Database
	err := row.Scan(
		&i.Name,
		&i.ProjectID,
		&i.User,
		&i.Password,
	)
	return i, err
}

const getGitHubApp = `-- name: GetGitHubApp :one
SELECT id, app_id, slug, private_key, webhook_secret, client_id, client_secret FROM github_app WHERE id = 1
`

func (q *Queries) GetGitHubApp(ctx context.Context) (GitHubApp, error) {
	row := q.db.QueryRowContext(ctx, getGitHubApp)
	var i GitHubApp
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Slug,
		&i.PrivateKey,
		&i.WebhookSecret,
		&i.ClientID,
		&i.ClientSecret,
	)
	return i, err
}

const getNotify = `-- name: GetNotify :one

SELECT id, email, sender_domain, zone_id, added_address, routed_domain, sender_name FROM notify WHERE id = 1
`

// Notifications
func (q *Queries) GetNotify(ctx context.Context) (Notify, error) {
	row := q.db.QueryRowContext(ctx, getNotify)
	var i Notify
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.SenderDomain,
		&i.ZoneID,
		&i.AddedAddress,
		&i.RoutedDomain,
		&i.SenderName,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, name, redirect_uris, created_at FROM oauth_clients WHERE id = ?
`

func (q *Queries) GetOAuthClient(ctx context.Context, id string) (OAuthClient, error) {
	row := q.db.QueryRowContext(ctx, getOAuthClient, id)
	var i OAuthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RedirectURIs,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthGrant = `-- name: GetOAuthGrant :one
SELECT id, client_id, client_name, redirect_uri, scope, github_id, created_at, last_used_at FROM oauth_grants WHERE id = ?
`

func (q *Queries) GetOAuthGrant(ctx context.Context, id int64) (OAuthGrant, error) {
	row := q.db.QueryRowContext(ctx, getOAuthGrant, id)
	var i OAuthGrant
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.RedirectURI,
		&i.Scope,
		&i.GitHubID,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT id, grant_id, kind, code_challenge, expires_at, used_at FROM oauth_tokens WHERE id = ?
`

func (q *Queries) GetOAuthToken(ctx context.Context, id string) (OAuthToken, error) {
	row := q.db.QueryRowContext(ctx, getOAuthToken, id)
	var i OAuthToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.Kind,
		&i.CodeChallenge,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getOwner = `-- name: GetOwner :one
SELECT github_id, github_login, github_email FROM owner WHERE id = 1
`

type GetOwnerRow struct {
	GitHubID    int64
	GitHubLogin string
	GitHubEmail string
}

func (q *Queries) GetOwner(ctx context.Context) (GetOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getOwner)
	var i GetOwnerRow
	err := row.Scan(&i.GitHubID, &i.GitHubLogin, &i.GitHubEmail)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, shared_env FROM projects WHERE name = ?
`

func (q *Queries) GetProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, name)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.SharedEnv)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, shared_env FROM projects WHERE id = ?
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.SharedEnv)
	return i, err
}

const getSessionRow = `-- name: GetSessionRow :one
SELECT id, github_id, signed_in_at, expires_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSessionRow(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionRow, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.GitHubID,
		&i.SignedInAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getStorage = `-- name: GetStorage :one
SELECT name, project_id, provider, account_id, endpoint, access_key_id, secret_access_key, bucket, region FROM storages WHERE name = ?
`

func (q *Queries) GetStorage(ctx context.Context, name string) (Storage, error) {
	row := q.db.QueryRowContext(ctx, getStorage, name)
	var i Storage
	err := row.Scan(
		&i.Name,
		&i.ProjectID,
		&i.Provider,
		&i.AccountID,
		&i.Endpoint,
		&i.AccessKeyID,
		&i.SecretAccessKey,
		&i.Bucket,
		&i.Region,
	)
	return i, err
}

const getVolumeBackup = `-- name: GetVolumeBackup :one
SELECT id, app_name, volume, object_key, parts, size_bytes, sha256, file_key, created_at, verified_at, verify_error, files FROM volume_backups WHERE id = ?
`

func (q *Queries) GetVolumeBackup(ctx context.Context, id int64) (VolumeBackup, error) {
	row := q.db.QueryRowContext(ctx, getVolumeBackup, id)
	var i VolumeBackup
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Volume,
		&i.ObjectKey,
		&i.Parts,
		&i.SizeBytes,
		&i.SHA256,
		&i.FileKey,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.VerifyError,
		&i.Files,
	)
	return i, err
}

const getWatchdog = `-- name: GetWatchdog :one

SELECT id, script, kv_namespace_id, created_at FROM watchdog WHERE id = 1
`

// Watchdog
func (q *Queries) GetWatchdog(ctx context.Context) (Watchdog, error) {
	row := q.db.QueryRowContext(ctx, getWatchdog)
	var i Watchdog
	err := row.Scan(
		&i.ID,
		&i.Script,
		&i.KvNamespaceID,
		&i.CreatedAt,
	)
	return i, err
}

const getWorker = `-- name: GetWorker :one
SELECT app_name, name, command, env FROM workers WHERE app_name = ?
`

func (q *Queries) GetWorker(ctx context.Context, appName string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorker, appName)
	var i Worker
	err := row.Scan(
		&i.AppName,
		&i.Name,
		&i.Command,
		&i.Env,
	)
	return i, err
}

const listAllBackups = `-- name: ListAllBackups :many
SELECT id, "database", object_key, parts, size_bytes, sha256, created_at, verified_at, verify_error, tables, file_key FROM backups WHERE database = ? ORDER BY id DESC
`

func (q *Queries) ListAllBackups(ctx context.Context, database string) ([]Backup, error) {
	rows, err := q.db.QueryContext(ctx, listAllBackups, database)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backup
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.Database,
			&i.ObjectKey,
			&i.Parts,
			&i.SizeBytes,
			&i.SHA256,
			&i.CreatedAt,
			&i.VerifiedAt,
			&i.VerifyError,
			&i.Tables,
			&i.FileKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSealedVars = `-- name: ListAllSealedVars :many
SELECT scope, owner, "key", value FROM sealed_vars ORDER BY scope, owner, key
`

func (q *Queries) ListAllSealedVars(ctx context.Context) ([]SealedVar, error) {
	rows, err := q.db.QueryContext(ctx, listAllSealedVars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SealedVar
	for rows.Next() {
		var i SealedVar
		if err := rows.Scan(
			&i.Scope,
			&i.Owner,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVolumeBackups = `-- name: ListAllVolumeBackups :many
SELECT id, app_name, volume, object_key, parts, size_bytes, sha256, file_key, created_at, verified_at, verify_error, files FROM volume_backups WHERE app_name = ? AND volume = ? ORDER BY id DESC
`

type ListAllVolumeBackupsParams struct {
	AppName string
	Volume  string
}

func (q *Queries) ListAllVolumeBackups(ctx context.Context, arg ListAllVolumeBackupsParams) ([]VolumeBackup, error) {
	rows, err := q.db.QueryContext(ctx, listAllVolumeBackups, arg.AppName, arg.Volume)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VolumeBackup
	for rows.Next() {
		var i VolumeBackup
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.Volume,
			&i.ObjectKey,
			&i.Parts,
			&i.SizeBytes,
			&i.SHA256,
			&i.FileKey,
			&i.CreatedAt,
			&i.VerifiedAt,
			&i.VerifyError,
			&i.Files,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVolumes = `-- name: ListAllVolumes :many
SELECT app_name, name, mount_path FROM volumes
`

func (q *Queries) ListAllVolumes(ctx context.Context) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listAllVolumes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(&i.AppName, &i.Name, &i.MountPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApps = `-- name: ListApps :many
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes, memory_mb, cpus, snapshot_db, snapshot_at FROM app_view ORDER BY name
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Name,
			&i.Repo,
			&i.Domain,
			&i.DnsZoneID,
			&i.DnsRecordID,
			&i.Port,
			&i.ContainerPort,
			&i.LivePort,
			&i.BuildPath,
			&i.BuildStrategy,
			&i.ActiveSlot,
			&i.Env,
			&i.SentryKey,
			&i.HealthCheckPath,
			&i.LinkedDB,
			&i.LinkedStorage,
			&i.ShareVolumes,
			&i.MemoryMB,
			&i.Cpus,
			&i.SnapshotDB,
			&i.SnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByProject = `-- name: ListAppsByProject :many
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes, memory_mb, cpus, snapshot_db, snapshot_at FROM app_view WHERE project_id = ? ORDER BY name
`

func (q *Queries) ListAppsByProject(ctx context.Context, projectID int64) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Name,
			&i.Repo,
			&i.Domain,
			&i.DnsZoneID,
			&i.DnsRecordID,
			&i.Port,
			&i.ContainerPort,
			&i.LivePort,
			&i.BuildPath,
			&i.BuildStrategy,
			&i.ActiveSlot,
			&i.Env,
			&i.SentryKey,
			&i.HealthCheckPath,
			&i.LinkedDB,
			&i.LinkedStorage,
			&i.ShareVolumes,
			&i.MemoryMB,
			&i.Cpus,
			&i.SnapshotDB,
			&i.SnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByRepo = `-- name: ListAppsByRepo :many
SELECT id, project_id, project_name, name, repo, domain, dns_zone_id, dns_record_id, port, container_port, live_port, build_path, build_strategy, active_slot, env, sentry_key, health_check_path, linked_db, linked_storage, share_volumes, memory_mb, cpus, snapshot_db, snapshot_at FROM app_view WHERE repo = ?
`

func (q *Queries) ListAppsByRepo(ctx context.Context, repo string) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByRepo, repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Name,
			&i.Repo,
			&i.Domain,
			&i.DnsZoneID,
			&i.DnsRecordID,
			&i.Port,
			&i.ContainerPort,
			&i.LivePort,
			&i.BuildPath,
			&i.BuildStrategy,
			&i.ActiveSlot,
			&i.Env,
			&i.SentryKey,
			&i.HealthCheckPath,
			&i.LinkedDB,
			&i.LinkedStorage,
			&i.ShareVolumes,
			&i.MemoryMB,
			&i.Cpus,
			&i.SnapshotDB,
			&i.SnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackups = `-- name: ListBackups :many
SELECT id, "database", object_key, parts, size_bytes, sha256, created_at, verified_at, verify_error, tables, file_key FROM backups WHERE database = ? ORDER BY id DESC LIMIT ?
`

type ListBackupsParams struct {
	Database string
	Limit    int64
}

func (q *Queries) ListBackups(ctx context.Context, arg ListBackupsParams) ([]Backup, error) {
	rows, err := q.db.QueryContext(ctx, listBackups, arg.Database, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backup
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.Database,
			&i.ObjectKey,
			&i.Parts,
			&i.SizeBytes,
			&i.SHA256,
			&i.CreatedAt,
			&i.VerifiedAt,
			&i.VerifyError,
			&i.Tables,
			&i.FileKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabases = `-- name: ListDatabases :many
SELECT name, project_id, db_user, db_password FROM databases ORDER BY name
`

func (q *Queries) ListDatabases(ctx context.Context) ([]Database, error) {
	rows, err := q.db.QueryContext(ctx, listDatabases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Database
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.Name,
			&i.ProjectID,
			&i.User,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByProject = `-- name: ListDatabasesByProject :many
SELECT name, project_id, db_user, db_password FROM databases WHERE project_id = ? ORDER BY name
`

func (q *Queries) ListDatabasesByProject(ctx context.Context, projectID int64) ([]Database, error) {
	rows, err := q.db.QueryContext(ctx, listDatabasesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Database
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.Name,
			&i.ProjectID,
			&i.User,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployLogs = `-- name: ListDeployLogs :many
SELECT id, app_name, trigger_source, status, output, created_at FROM deploy_logs WHERE app_name = ? ORDER BY id DESC LIMIT ?
`

type ListDeployLogsParams struct {
	AppName string
	Limit   int64
}

func (q *Queries) ListDeployLogs(ctx context.Context, arg ListDeployLogsParams) ([]DeployLog, error) {
	rows, err := q.db.QueryContext(ctx, listDeployLogs, arg.AppName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeployLog
	for rows.Next() {
		var i DeployLog
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.Trigger,
			&i.Status,
			&i.Output,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOAuthGrants = `-- name: ListOAuthGrants :many
SELECT id, client_id, client_name, redirect_uri, scope, github_id, created_at, last_used_at FROM oauth_grants g
WHERE EXISTS (SELECT 1 FROM oauth_tokens t WHERE t.grant_id = g.id AND t.kind != 'code' AND t.used_at = '' AND t.expires_at >= ?)
ORDER BY g.id DESC
`

// Grants with a token still alive, newest first.
func (q *Queries) ListOAuthGrants(ctx context.Context, expiresAt string) ([]OAuthGrant, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthGrants, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OAuthGrant
	for rows.Next() {
		var i OAuthGrant
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.RedirectURI,
			&i.Scope,
			&i.GitHubID,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, shared_env FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ID, &i.Name, &i.SharedEnv); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningDeployLogs = `-- name: ListRunningDeployLogs :many
SELECT id, output FROM deploy_logs WHERE status = 'running'
`

type ListRunningDeployLogsRow struct {
	ID     int64
	Output secret.String
}

func (q *Queries) ListRunningDeployLogs(ctx context.Context) ([]ListRunningDeployLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningDeployLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunningDeployLogsRow
	for rows.Next() {
		var i ListRunningDeployLogsRow
		if err := rows.Scan(&i.ID, &i.Output); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSealedVars = `-- name: ListSealedVars :many
SELECT scope, owner, "key", value FROM sealed_vars WHERE scope = ? AND owner = ? ORDER BY key
`

type ListSealedVarsParams struct {
	Scope string
	Owner string
}

func (q *Queries) ListSealedVars(ctx context.Context, arg ListSealedVarsParams) ([]SealedVar, error) {
	rows, err := q.db.QueryContext(ctx, listSealedVars, arg.Scope, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SealedVar
	for rows.Next() {
		var i SealedVar
		if err := rows.Scan(
			&i.Scope,
			&i.Owner,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorages = `-- name: ListStorages :many
SELECT name, project_id, provider, account_id, endpoint, access_key_id, secret_access_key, bucket, region FROM storages ORDER BY name
`

func (q *Queries) ListStorages(ctx context.Context) ([]Storage, error) {
	rows, err := q.db.QueryContext(ctx, listStorages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Storage
	for rows.Next() {
		var i Storage
		if err := rows.Scan(
			&i.Name,
			&i.ProjectID,
			&i.Provider,
			&i.AccountID,
			&i.Endpoint,
			&i.AccessKeyID,
			&i.SecretAccessKey,
			&i.Bucket,
			&i.Region,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoragesByProject = `-- name: ListStoragesByProject :many
SELECT name, project_id, provider, account_id, endpoint, access_key_id, secret_access_key, bucket, region FROM storages WHERE project_id = ? ORDER BY name
`

func (q *Queries) ListStoragesByProject(ctx context.Context, projectID int64) ([]Storage, error) {
	rows, err := q.db.QueryContext(ctx, listStoragesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Storage
	for rows.Next() {
		var i Storage
		if err := rows.Scan(
			&i.Name,
			&i.ProjectID,
			&i.Provider,
			&i.AccountID,
			&i.Endpoint,
			&i.AccessKeyID,
			&i.SecretAccessKey,
			&i.Bucket,
			&i.Region,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumeBackups = `-- name: ListVolumeBackups :many
SELECT id, app_name, volume, object_key, parts, size_bytes, sha256, file_key, created_at, verified_at, verify_error, files FROM volume_backups WHERE app_name = ? AND volume = ? ORDER BY id DESC LIMIT ?
`

type ListVolumeBackupsParams struct {
	AppName string
	Volume  string
	Limit   int64
}

func (q *Queries) ListVolumeBackups(ctx context.Context, arg ListVolumeBackupsParams) ([]VolumeBackup, error) {
	rows, err := q.db.QueryContext(ctx, listVolumeBackups, arg.AppName, arg.Volume, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VolumeBackup
	for rows.Next() {
		var i VolumeBackup
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.Volume,
			&i.ObjectKey,
			&i.Parts,
			&i.SizeBytes,
			&i.SHA256,
			&i.FileKey,
			&i.CreatedAt,
			&i.VerifiedAt,
			&i.VerifyError,
			&i.Files,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumes = `-- name: ListVolumes :many
SELECT app_name, name, mount_path FROM volumes WHERE app_name = ? ORDER BY name
`

func (q *Queries) ListVolumes(ctx context.Context, appName string) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listVolumes, appName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(&i.AppName, &i.Name, &i.MountPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noteWebhookDelivery = `-- name: NoteWebhookDelivery :execrows

INSERT OR IGNORE INTO webhook_deliveries (id) VALUES (?)
`

// Webhooks
// 0 rows: the delivery was handled before.
func (q *Queries) NoteWebhookDelivery(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, noteWebhookDelivery, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneDeployLogs = `-- name: PruneDeployLogs :exec
DELETE FROM deploy_logs WHERE created_at < ?
`

func (q *Queries) PruneDeployLogs(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, pruneDeployLogs, createdAt)
	return err
}

const pruneOAuthClients = `-- name: PruneOAuthClients :exec
DELETE FROM oauth_clients
WHERE oauth_clients.created_at < ? AND oauth_clients.id NOT IN (SELECT client_id FROM oauth_grants)
`

func (q *Queries) PruneOAuthClients(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, pruneOAuthClients, createdAt)
	return err
}

const pruneOAuthGrants = `-- name: PruneOAuthGrants :exec
DELETE FROM oauth_grants
WHERE NOT EXISTS (SELECT 1 FROM oauth_tokens t WHERE t.grant_id = oauth_grants.id AND t.expires_at >= ?)
`

// Grants none of whose tokens can be used any more.
func (q *Queries) PruneOAuthGrants(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, pruneOAuthGrants, expiresAt)
	return err
}

const pruneOAuthTokens = `-- name: PruneOAuthTokens :exec
DELETE FROM oauth_tokens WHERE expires_at < ?
`

func (q *Queries) PruneOAuthTokens(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, pruneOAuthTokens, expiresAt)
	return err
}

const pruneWebhookDeliveries = `-- name: PruneWebhookDeliveries :exec
DELETE FROM webhook_deliveries WHERE created_at < ?
`

func (q *Queries) PruneWebhookDeliveries(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, pruneWebhookDeliveries, createdAt)
	return err
}

const saveCloudflareToken = `-- name: SaveCloudflareToken :exec
INSERT INTO cloudflare (id, api_token) VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET api_token = excluded.api_token
`

func (q *Queries) SaveCloudflareToken(ctx context.Context, apiToken secret.String) error {
	_, err := q.db.ExecContext(ctx, saveCloudflareToken, apiToken)
	return err
}

const saveCloudflareTunnel = `-- name: SaveCloudflareTunnel :exec
UPDATE cloudflare SET account_id = ?, tunnel_id = ?, tunnel_token = ?, panel_zone_id = ?, panel_record_id = ? WHERE id = 1
`

type SaveCloudflareTunnelParams struct {
	AccountID     string
	TunnelID      string
	TunnelToken   secret.String
	PanelZoneID   string
	PanelRecordID string
}

func (q *Queries) SaveCloudflareTunnel(ctx context.Context, arg SaveCloudflareTunnelParams) error {
	_, err := q.db.ExecContext(ctx, saveCloudflareTunnel,
		arg.AccountID,
		arg.TunnelID,
		arg.TunnelToken,
		arg.PanelZoneID,
		arg.PanelRecordID,
	)
	return err
}

const saveGitHubApp = `-- name: SaveGitHubApp :exec

INSERT OR REPLACE INTO github_app (id, app_id, slug, private_key, webhook_secret, client_id, client_secret)
VALUES (1, ?, ?, ?, ?, ?, ?)
`

type SaveGitHubAppParams struct {
	AppID         int64
	Slug          string
	PrivateKey    secret.String
	WebhookSecret secret.String
	ClientID      string
	ClientSecret  secret.String
}

// GitHub App and the owner
func (q *Queries) SaveGitHubApp(ctx context.Context, arg SaveGitHubAppParams) error {
	_, err := q.db.ExecContext(ctx, saveGitHubApp,
		arg.AppID,
		arg.Slug,
		arg.PrivateKey,
		arg.WebhookSecret,
		arg.ClientID,
		arg.ClientSecret,
	)
	return err
}

const saveNotify = `-- name: SaveNotify :exec
INSERT INTO notify (id, email, sender_name, sender_domain, zone_id, added_address, routed_domain) VALUES (1, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET email = excluded.email, sender_name = excluded.sender_name, sender_domain = excluded.sender_domain,
	zone_id = excluded.zone_id, added_address = excluded.added_address, routed_domain = excluded.routed_domain
`

type SaveNotifyParams struct {
	Email        string
	SenderName   string
	SenderDomain string
	ZoneID       string
	AddedAddress int64
	RoutedDomain string
}

func (q *Queries) SaveNotify(ctx context.Context, arg SaveNotifyParams) error {
	_, err := q.db.ExecContext(ctx, saveNotify,
		arg.Email,
		arg.SenderName,
		arg.SenderDomain,
		arg.ZoneID,
		arg.AddedAddress,
		arg.RoutedDomain,
	)
	return err
}

const saveWatchdog = `-- name: SaveWatchdog :exec
INSERT INTO watchdog (id, script, kv_namespace_id) VALUES (1, ?, ?)
ON CONFLICT (id) DO UPDATE SET script = excluded.script, kv_namespace_id = excluded.kv_namespace_id
`

type SaveWatchdogParams struct {
	Script        string
	KvNamespaceID string
}

func (q *Queries) SaveWatchdog(ctx context.Context, arg SaveWatchdogParams) error {
	_, err := q.db.ExecContext(ctx, saveWatchdog, arg.Script, arg.KvNamespaceID)
	return err
}

const saveWorker = `-- name: SaveWorker :exec

INSERT INTO workers (app_name, name, command, env) VALUES (?, ?, ?, ?)
ON CONFLICT(app_name) DO UPDATE SET name = excluded.name, command = excluded.command, env = excluded.env
`

type SaveWorkerParams struct {
	AppName string
	Name    string
	Command secret.String
	Env     secret.String
}

// Workers
func (q *Queries) SaveWorker(ctx context.Context, arg SaveWorkerParams) error {
	_, err := q.db.ExecContext(ctx, saveWorker,
		arg.AppName,
		arg.Name,
		arg.Command,
		arg.Env,
	)
	return err
}

const setAppBuild = `-- name: SetAppBuild :exec
UPDATE apps SET build_path = ?, build_strategy = ? WHERE name = ?
`

type SetAppBuildParams struct {
	BuildPath     string
	BuildStrategy string
	Name          string
}

func (q *Queries) SetAppBuild(ctx context.Context, arg SetAppBuildParams) error {
	_, err := q.db.ExecContext(ctx, setAppBuild, arg.BuildPath, arg.BuildStrategy, arg.Name)
	return err
}

const setAppDomain = `-- name: SetAppDomain :exec
UPDATE apps SET domain = ?, dns_zone_id = ?, dns_record_id = ? WHERE name = ?
`

type SetAppDomainParams struct {
	Domain      string
	DnsZoneID   string
	DnsRecordID string
	Name        string
}

func (q *Queries) SetAppDomain(ctx context.Context, arg SetAppDomainParams) error {
	_, err := q.db.ExecContext(ctx, setAppDomain,
		arg.Domain,
		arg.DnsZoneID,
		arg.DnsRecordID,
		arg.Name,
	)
	return err
}

const setAppEnv = `-- name: SetAppEnv :exec
UPDATE apps SET env = ? WHERE name = ?
`

type SetAppEnvParams struct {
	Env  secret.String
	Name string
}

func (q *Queries) SetAppEnv(ctx context.Context, arg SetAppEnvParams) error {
	_, err := q.db.ExecContext(ctx, setAppEnv, arg.Env, arg.Name)
	return err
}

const setAppLimits = `-- name: SetAppLimits :exec
UPDATE apps SET memory_mb = ?, cpus = ? WHERE name = ?
`

type SetAppLimitsParams struct {
	MemoryMB int64
	Cpus     float64
	Name     string
}

func (q *Queries) SetAppLimits(ctx context.Context, arg SetAppLimitsParams) error {
	_, err := q.db.ExecContext(ctx, setAppLimits, arg.MemoryMB, arg.Cpus, arg.Name)
	return err
}

const setAppLinkedDB = `-- name: SetAppLinkedDB :exec
UPDATE apps SET linked_db = ? WHERE name = ?
`

type SetAppLinkedDBParams struct {
	LinkedDB string
	Name     string
}

func (q *Queries) SetAppLinkedDB(ctx context.Context, arg SetAppLinkedDBParams) error {
	_, err := q.db.ExecContext(ctx, setAppLinkedDB, arg.LinkedDB, arg.Name)
	return err
}

const setAppLinkedStorage = `-- name: SetAppLinkedStorage :exec
UPDATE apps SET linked_storage = ? WHERE name = ?
`

type SetAppLinkedStorageParams struct {
	LinkedStorage string
	Name          string
}

func (q *Queries) SetAppLinkedStorage(ctx context.Context, arg SetAppLinkedStorageParams) error {
	_, err := q.db.ExecContext(ctx, setAppLinkedStorage, arg.LinkedStorage, arg.Name)
	return err
}

const setAppLive = `-- name: SetAppLive :exec
UPDATE apps SET active_slot = ?, live_port = ? WHERE name = ?
`

type SetAppLiveParams struct {
	ActiveSlot string
	LivePort   int64
	Name       string
}

func (q *Queries) SetAppLive(ctx context.Context, arg SetAppLiveParams) error {
	_, err := q.db.ExecContext(ctx, setAppLive, arg.ActiveSlot, arg.LivePort, arg.Name)
	return err
}

const setAppSentryKey = `-- name: SetAppSentryKey :exec
UPDATE apps SET sentry_key = ? WHERE name = ?
`

type SetAppSentryKeyParams struct {
	SentryKey secret.String
	Name      string
}

func (q *Queries) SetAppSentryKey(ctx context.Context, arg SetAppSentryKeyParams) error {
	_, err := q.db.ExecContext(ctx, setAppSentryKey, arg.SentryKey, arg.Name)
	return err
}

const setAppSettings = `-- name: SetAppSettings :exec
UPDATE apps SET container_port = ?, health_check_path = ? WHERE name = ?
`

type SetAppSettingsParams struct {
	ContainerPort   int64
	HealthCheckPath string
	Name            string
}

func (q *Queries) SetAppSettings(ctx context.Context, arg SetAppSettingsParams) error {
	_, err := q.db.ExecContext(ctx, setAppSettings, arg.ContainerPort, arg.HealthCheckPath, arg.Name)
	return err
}

const setAppShareVolumes = `-- name: SetAppShareVolumes :exec
UPDATE apps SET share_volumes = ? WHERE name = ?
`

type SetAppShareVolumesParams struct {
	ShareVolumes int64
	Name         string
}

func (q *Queries) SetAppShareVolumes(ctx context.Context, arg SetAppShareVolumesParams) error {
	_, err := q.db.ExecContext(ctx, setAppShareVolumes, arg.ShareVolumes, arg.Name)
	return err
}

const setAppSnapshot = `-- name: SetAppSnapshot :exec
UPDATE apps SET snapshot_db = ?, snapshot_at = ? WHERE name = ?
`

type SetAppSnapshotParams struct {
	SnapshotDB string
	SnapshotAt string
	Name       string
}

func (q *Queries) SetAppSnapshot(ctx context.Context, arg SetAppSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, setAppSnapshot, arg.SnapshotDB, arg.SnapshotAt, arg.Name)
	return err
}

const setBackupBucket = `-- name: SetBackupBucket :exec
UPDATE cloudflare SET backup_bucket = ? WHERE id = 1
`

func (q *Queries) SetBackupBucket(ctx context.Context, backupBucket string) error {
	_, err := q.db.ExecContext(ctx, setBackupBucket, backupBucket)
	return err
}

const setBackupVerified = `-- name: SetBackupVerified :exec
UPDATE backups SET verified_at = ?, verify_error = ?, tables = ? WHERE id = ?
`

type SetBackupVerifiedParams struct {
	VerifiedAt  string
	VerifyError string
	Tables      int64
	ID          int64
}

func (q *Queries) SetBackupVerified(ctx context.Context, arg SetBackupVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, setBackupVerified,
		arg.VerifiedAt,
		arg.VerifyError,
		arg.Tables,
		arg.ID,
	)
	return err
}

const setDatabasePassword = `-- name: SetDatabasePassword :exec
UPDATE databases SET db_password = ? WHERE name = ?
`

type SetDatabasePasswordParams struct {
	Password secret.String
	Name     string
}

func (q *Queries) SetDatabasePassword(ctx context.Context, arg SetDatabasePasswordParams) error {
	_, err := q.db.ExecContext(ctx, setDatabasePassword, arg.Password, arg.Name)
	return err
}

const setGitHubWebhookSecret = `-- name: SetGitHubWebhookSecret :exec
UPDATE github_app SET webhook_secret = ? WHERE id = 1
`

func (q *Queries) SetGitHubWebhookSecret(ctx context.Context, webhookSecret secret.String) error {
	_, err := q.db.ExecContext(ctx, setGitHubWebhookSecret, webhookSecret)
	return err
}

const setOwner = `-- name: SetOwner :exec
INSERT INTO owner (id, github_id, github_login) VALUES (1, ?, ?)
`

type SetOwnerParams struct {
	GitHubID    int64
	GitHubLogin string
}

func (q *Queries) SetOwner(ctx context.Context, arg SetOwnerParams) error {
	_, err := q.db.ExecContext(ctx, setOwner, arg.GitHubID, arg.GitHubLogin)
	return err
}

const setOwnerEmail = `-- name: SetOwnerEmail :exec
UPDATE owner SET github_email = ? WHERE id = 1
`

func (q *Queries) SetOwnerEmail(ctx context.Context, githubEmail string) error {
	_, err := q.db.ExecContext(ctx, setOwnerEmail, githubEmail)
	return err
}

const setOwnerLogin = `-- name: SetOwnerLogin :exec
UPDATE owner SET github_login = ? WHERE id = 1
`

func (q *Queries) SetOwnerLogin(ctx context.Context, githubLogin string) error {
	_, err := q.db.ExecContext(ctx, setOwnerLogin, githubLogin)
	return err
}

const setProjectSharedEnv = `-- name: SetProjectSharedEnv :exec
UPDATE projects SET shared_env = ? WHERE name = ?
`

type SetProjectSharedEnvParams struct {
	SharedEnv secret.String
	Name      string
}

func (q *Queries) SetProjectSharedEnv(ctx context.Context, arg SetProjectSharedEnvParams) error {
	_, err := q.db.ExecContext(ctx, setProjectSharedEnv, arg.SharedEnv, arg.Name)
	return err
}

const setSealedVar = `-- name: SetSealedVar :exec

INSERT INTO sealed_vars (scope, owner, key, value) VALUES (?, ?, ?, ?)
ON CONFLICT(scope, owner, key) DO UPDATE SET value = excluded.value
`

type SetSealedVarParams struct {
	Scope string
	Owner string
	Key   string
	Value secret.String
}

// Sealed variables
func (q *Queries) SetSealedVar(ctx context.Context, arg SetSealedVarParams) error {
	_, err := q.db.ExecContext(ctx, setSealedVar,
		arg.Scope,
		arg.Owner,
		arg.Key,
		arg.Value,
	)
	return err
}

const setStorageKeys = `-- name: SetStorageKeys :exec
UPDATE storages SET access_key_id = ?, secret_access_key = ? WHERE name = ?
`

type SetStorageKeysParams struct {
	AccessKeyID     string
	SecretAccessKey secret.String
	Name            string
}

func (q *Queries) SetStorageKeys(ctx context.Context, arg SetStorageKeysParams) error {
	_, err := q.db.ExecContext(ctx, setStorageKeys, arg.AccessKeyID, arg.SecretAccessKey, arg.Name)
	return err
}

const setTunnelToken = `-- name: SetTunnelToken :exec
UPDATE cloudflare SET tunnel_token = ? WHERE id = 1
`

func (q *Queries) SetTunnelToken(ctx context.Context, tunnelToken secret.String) error {
	_, err := q.db.ExecContext(ctx, setTunnelToken, tunnelToken)
	return err
}

const setVolumeBackupVerified = `-- name: SetVolumeBackupVerified :exec
UPDATE volume_backups SET verified_at = ?, verify_error = ?, files = ? WHERE id = ?
`

type SetVolumeBackupVerifiedParams struct {
	VerifiedAt  string
	VerifyError string
	Files       int64
	ID          int64
}

func (q *Queries) SetVolumeBackupVerified(ctx context.Context, arg SetVolumeBackupVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, setVolumeBackupVerified,
		arg.VerifiedAt,
		arg.VerifyError,
		arg.Files,
		arg.ID,
	)
	return err
}

const touchOAuthGrant = `-- name: TouchOAuthGrant :exec
UPDATE oauth_grants SET last_used_at = ? WHERE id = ?
`

type TouchOAuthGrantParams struct {
	LastUsedAt string
	ID         int64
}

func (q *Queries) TouchOAuthGrant(ctx context.Context, arg TouchOAuthGrantParams) error {
	_, err := q.db.ExecContext(ctx, touchOAuthGrant, arg.LastUsedAt, arg.ID)
	return err
}

const updateDeployLog = `-- name: UpdateDeployLog :exec
UPDATE deploy_logs SET status = ?, output = ? WHERE id = ?
`

type UpdateDeployLogParams struct {
	Status string
	Output secret.String
	ID     int64
}

func (q *Queries) UpdateDeployLog(ctx context.Context, arg UpdateDeployLogParams) error {
	_, err := q.db.ExecContext(ctx, updateDeployLog, arg.Status, arg.Output, arg.ID)
	return err
}

const useOAuthToken = `-- name: UseOAuthToken :execrows
UPDATE oauth_tokens SET used_at = ? WHERE id = ? AND used_at = ''
`

type UseOAuthTokenParams struct {
	UsedAt string
	ID     string
}

// Marks a code or refresh token exchanged; 0 rows if it was already.
func (q *Queries) UseOAuthToken(ctx context.Context, arg UseOAuthTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useOAuthToken, arg.UsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
